import { TargetLevel } from "../types";

export interface InteractionItem {
  id: string;
  topic: string;
  level: TargetLevel;
  situationRu: string; // scene-setting context in Russian — interaction competence depends on
  // reading the social situation correctly, not just the words
  dialogue: string[]; // preceding lines of the exchange, in order
  options: string[]; // candidate responses for the learner's turn
  correctIndex: number;
  explanationRu: string;
}

// §2/§10 — "interaction" is CEFR's dialogic-exchange skill, distinct from
// monologic "speaking": responding appropriately inside a live exchange
// (requesting, clarifying, declining, agreeing) rather than producing a
// planned utterance alone. Kept as constrained response-selection, never a
// free-form chat tutor — that's explicitly out of scope (§1): an
// unconstrained model accepts ungrammatical/unnatural input when intent is
// recoverable, which is the opposite of what this skill should train.
export const INTERACTION_ITEMS: InteractionItem[] = [
  {
    id: "int-1",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы записаться к врачу.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk, waarmee kan ik u helpen?"],
    options: [
      "Ik wil graag een afspraak maken.",
      "Ik ben de huisarts.",
      "Nee, dank u wel.",
    ],
    correctIndex: 0,
    explanationRu: "Прямая и вежливая формула для записи на приём — 'Ik wil graag een afspraak maken'.",
  },
  {
    id: "int-2",
    topic: "huisarts",
    level: "A2",
    situationRu: "Ассистент спрашивает, когда вам удобно.",
    dialogue: ["Assistente: Wanneer komt het u uit?", "U: Kan het deze week nog?", "Assistente: Ja, donderdag om elf uur kan."],
    options: ["Nee, dat wil ik niet.", "Goed, dan zie ik u donderdag om elf uur.", "Ik weet het niet."],
    correctIndex: 1,
    explanationRu: "Нужно подтвердить и повторить договорённость — это стандартный способ закрыть тему по телефону.",
  },
  {
    id: "int-3",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы не расслышали, что сказал сотрудник, и просите повторить.",
    dialogue: ["Ambtenaar: U moet dit formulier binnen twee weken opsturen."],
    options: [
      "Sorry, kunt u dat herhalen?",
      "Ja, dat weet ik al lang.",
      "Nee, dat doe ik nooit.",
    ],
    correctIndex: 0,
    explanationRu: "'Kunt u dat herhalen?' — вежливая просьба повторить, стандартная формула при непонимании.",
  },
  {
    id: "int-4",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы не понимаете слово в объяснении сотрудника гемeente.",
    dialogue: ["Ambtenaar: U heeft een uittreksel uit de basisregistratie nodig."],
    options: [
      "Wat betekent 'uittreksel'?",
      "Dat is heel duidelijk, bedankt.",
      "Ik ga naar huis.",
    ],
    correctIndex: 0,
    explanationRu: "Прямой вопрос о значении слова — рабочая стратегия при незнакомой лексике, а не делать вид, что всё понятно.",
  },
  {
    id: "int-5",
    topic: "afspraak_verzetten",
    level: "A2",
    situationRu: "Вам нужно отменить или перенести приём.",
    dialogue: ["U belt de praktijk.", "Assistente: Waarmee kan ik u helpen?"],
    options: [
      "Ik kan donderdag niet, kan het naar een andere dag?",
      "Ik kom morgen zeker.",
      "Ik heb geen afspraak nodig.",
    ],
    correctIndex: 0,
    explanationRu: "Просьба перенести встречу с указанием причины/ограничения — уместный ответ в этой ситуации.",
  },
  {
    id: "int-6",
    topic: "werk",
    level: "B1",
    situationRu: "Собеседование при приёме на работу — вас просят представиться.",
    dialogue: ["Werkgever: Kunt u zich even voorstellen?"],
    options: [
      "Ik heet Anna en ik werk graag met mensen.",
      "Waarom vraagt u dat?",
      "Dat is privé.",
    ],
    correctIndex: 0,
    explanationRu: "На собеседовании ожидается краткое, доброжелательное представление себя.",
  },
  {
    id: "int-7",
    topic: "werk",
    level: "B1",
    situationRu: "Работодатель спрашивает про ваш опыт.",
    dialogue: ["Werkgever: Heeft u al werkervaring in Nederland?", "U: Nog niet, maar ik heb wel ervaring uit mijn eigen land."],
    options: [
      "Kunt u daar iets meer over vertellen?",
      "Dat interesseert mij niet.",
      "Ik stop met dit gesprek.",
    ],
    correctIndex: 0,
    explanationRu: "Естественная реакция интервьюера — просьба рассказать подробнее; это пример уместной реплики-продолжения.",
  },
  {
    id: "int-8",
    topic: "wonen",
    level: "A2",
    situationRu: "У вас сломалось отопление, вы звоните хозяину жилья.",
    dialogue: ["Verhuurder: Wat is het probleem?"],
    options: [
      "De verwarming werkt niet meer.",
      "Ik wil een nieuwe woning.",
      "Alles is goed, bedankt.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко назвать проблему — первый шаг в обращении с жалобой/просьбой о ремонте.",
  },
  {
    id: "int-9",
    topic: "wonen",
    level: "A2",
    situationRu: "Хозяин жилья спрашивает, когда удобно, чтобы прийти мастер.",
    dialogue: ["Verhuurder: Wanneer kan de monteur langskomen?"],
    options: [
      "Morgenochtend komt mij goed uit.",
      "Ik weet het niet en het maakt niet uit.",
      "Nooit, ik ben altijd weg.",
    ],
    correctIndex: 0,
    explanationRu: "Конкретное предложение времени — конструктивный, вежливый ответ.",
  },
  {
    id: "int-10",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед здоровается с вами во дворе.",
    dialogue: ["Buurman: Goedemorgen! Alles goed?"],
    options: [
      "Goedemorgen, met mij gaat het goed, en met u?",
      "Ik ken u niet.",
      "Wat wilt u van mij?",
    ],
    correctIndex: 0,
    explanationRu: "Стандартный обмен приветствиями с встречным вопросом — база вежливого small talk.",
  },
  {
    id: "int-11",
    topic: "buurt",
    level: "A2",
    situationRu: "Разговор с соседом заканчивается, вам нужно идти.",
    dialogue: ["Buurman: Nou, leuk je gesproken te hebben!"],
    options: [
      "Ja, insgelijks! Tot ziens.",
      "Ik ga nooit meer met u praten.",
      "Dat weet ik niet.",
    ],
    correctIndex: 0,
    explanationRu: "'Insgelijks' (взаимно) + прощание — естественное завершение короткого разговора.",
  },
  {
    id: "int-12",
    topic: "documenten",
    level: "B1",
    situationRu: "Вы получили письмо от гемeente и не всё поняли.",
    dialogue: ["U belt de gemeente.", "Ambtenaar: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een brief gekregen, maar ik begrijp een deel niet.",
      "Ik heb niets gekregen van u, dat is een leugen.",
      "Stuur mij nog honderd brieven.",
    ],
    correctIndex: 0,
    explanationRu: "Прямое и вежливое объяснение цели звонка — оптимальный первый ход разговора.",
  },
  {
    id: "int-13",
    topic: "documenten",
    level: "B1",
    situationRu: "Сотрудник просит уточнить, какой именно документ вам нужен.",
    dialogue: ["Ambtenaar: Welk document heeft u precies nodig?"],
    options: [
      "Ik heb een uittreksel uit het bevolkingsregister nodig.",
      "Een document, gewoon een document.",
      "Dat maakt niet uit voor mij.",
    ],
    correctIndex: 0,
    explanationRu: "Конкретизация запроса — важный навык взаимодействия с официальными учреждениями.",
  },
  {
    id: "int-14",
    topic: "geld",
    level: "B1",
    situationRu: "Вы не согласны с суммой в счёте.",
    dialogue: ["Klantenservice: Wat kan ik voor u doen?"],
    options: [
      "Ik denk dat er een fout staat in mijn rekening.",
      "Uw bedrijf is heel slecht.",
      "Ik betaal nooit meer iets.",
    ],
    correctIndex: 0,
    explanationRu: "Формулировка несогласия без агрессии — 'ik denk dat er een fout staat' звучит уважительно и по делу.",
  },
  {
    id: "int-15",
    topic: "geld",
    level: "B1",
    situationRu: "Вас просят прислать подтверждение оплаты.",
    dialogue: ["Klantenservice: Kunt u een bewijs van betaling sturen?"],
    options: [
      "Ja, dat stuur ik vandaag nog op.",
      "Waarom zou ik dat doen?",
      "Ik heb geen tijd voor u.",
    ],
    correctIndex: 0,
    explanationRu: "Согласие с конкретным сроком — конструктивная и вежливая реакция на просьбу.",
  },
  {
    id: "int-16",
    topic: "dagelijks_leven",
    level: "A2",
    situationRu: "Вы опоздали на встречу и извиняетесь.",
    dialogue: ["Collega: Je bent laat, wat is er gebeurd?"],
    options: [
      "Sorry, ik stond vast in het verkeer.",
      "Dat gaat u niets aan.",
      "Ik ben nooit laat.",
    ],
    correctIndex: 0,
    explanationRu: "Извинение + краткое объяснение причины — стандартная вежливая реакция на опоздание.",
  },
  {
    id: "int-17",
    topic: "dagelijks_leven",
    level: "A2",
    situationRu: "Собеседник предлагает встретиться в другой день.",
    dialogue: ["Collega: Zullen we het dan volgende week doen?"],
    options: [
      "Ja, dat is goed, welke dag komt jou uit?",
      "Nee, ik wil nooit meer afspreken.",
      "Dat begrijp ik niet.",
    ],
    correctIndex: 0,
    explanationRu: "Согласие + встречный вопрос о деталях — естественное продолжение договорённости.",
  },
  {
    id: "int-18",
    topic: "dagelijks_leven",
    level: "A2",
    situationRu: "Вы хотите вежливо не согласиться с предложением.",
    dialogue: ["Vriend: Zullen we morgen om zeven uur 's ochtends afspreken?"],
    options: [
      "Dat is best vroeg voor mij, kan het ook wat later?",
      "Nee, dat doe ik nooit, punt uit.",
      "Ik vind u een slecht persoon.",
    ],
    correctIndex: 0,
    explanationRu: "Мягкое несогласие с альтернативой — вежливая формула вместо прямого отказа.",
  },
  {
    id: "int-19",
    topic: "gemeente",
    level: "A2",
    situationRu: "Сотрудник уточняет ваш адрес.",
    dialogue: ["Ambtenaar: Kunt u uw adres bevestigen?"],
    options: [
      "Ja, dat is Kerkstraat 12 in Utrecht.",
      "Waarom wilt u dat weten?",
      "Ik woon nergens.",
    ],
    correctIndex: 0,
    explanationRu: "Прямое подтверждение с конкретными данными — то, чего ждёт собеседник.",
  },
  {
    id: "int-20",
    topic: "geld",
    level: "A2",
    situationRu: "Вы просите чек/квитанцию в магазине.",
    dialogue: ["Verkoper: Alstublieft, dat is dan vijftien euro.", "U betaalt.", "Verkoper: Nog een fijne dag!"],
    options: [
      "Mag ik ook een bonnetje, alstublieft?",
      "Ik wil mijn geld terug, nu meteen.",
      "Dat is te duur, ik betaal niet.",
    ],
    correctIndex: 0,
    explanationRu: "Простая вежливая просьба о квитанции — распространённая бытовая фраза.",
  },
  {
    id: "int-21",
    topic: "werk",
    level: "B1",
    situationRu: "Заканчивается телефонный разговор с работодателем.",
    dialogue: ["Werkgever: We nemen volgende week contact met u op.", "U:"],
    options: [
      "Dank u wel, ik hoor het graag van u. Fijne dag nog!",
      "Oké, doei.",
      "Waarom moet ik wachten?",
    ],
    correctIndex: 0,
    explanationRu: "Официально-вежливое завершение делового разговора — благодарность и пожелание, а не разговорное 'doei'.",
  },
  {
    id: "int-22",
    topic: "wonen",
    level: "A2",
    situationRu: "Вы забыли ключ и просите соседа впустить вас.",
    dialogue: ["Buurman: Wat is er aan de hand?"],
    options: [
      "Ik ben mijn sleutel vergeten, mag ik even wachten bij u?",
      "Geef mij nu uw sleutel.",
      "Dat is niet uw probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Объяснение ситуации + вежливая просьба — уместная реакция, не требование.",
  },
  {
    id: "int-23",
    topic: "gezondheid",
    level: "A2",
    situationRu: "Врач спрашивает о симптомах.",
    dialogue: ["Dokter: Wat zijn uw klachten?"],
    options: [
      "Ik heb al twee dagen hoofdpijn en koorts.",
      "Ik weet het niet, u bent de dokter.",
      "Dat vertel ik niet.",
    ],
    correctIndex: 0,
    explanationRu: "Конкретное описание симптомов — то, что нужно врачу для помощи.",
  },
  {
    id: "int-24",
    topic: "gezondheid",
    level: "A2",
    situationRu: "Врач предлагает выписать рецепт.",
    dialogue: ["Dokter: Ik schrijf u een recept voor.", "U:"],
    options: [
      "Dank u wel, waar kan ik het medicijn ophalen?",
      "Ik wil geen medicijnen, punt uit.",
      "Dat is niet nodig, ik voel me prima."
    ],
    correctIndex: 0,
    explanationRu: "Благодарность + уточняющий вопрос — естественное продолжение диалога у врача.",
  },
  {
    id: "int-25",
    topic: "onderwijs",
    level: "A2",
    situationRu: "Преподаватель спрашивает, понятен ли материал.",
    dialogue: ["Docent: Is alles duidelijk, of heeft iemand nog vragen?"],
    options: [
      "Ik heb een vraag over de vorige les.",
      "Nee, dat interesseert mij niet.",
      "Ik kom niet meer naar de les.",
    ],
    correctIndex: 0,
    explanationRu: "Конкретный вопрос по теме — ожидаемая и уместная реакция на приглашение задать вопросы.",
  },
  {
    id: "int-26",
    topic: "geld",
    level: "B1",
    situationRu: "Сотрудник банка спрашивает про открытие полиса.",
    dialogue: ["Medewerker: Wilt u ook een verzekering afsluiten?"],
    options: [
      "Kunt u me eerst vertellen wat de kosten zijn?",
      "Ja, doe maar alles wat u heeft.",
      "Nee, ik heb geen interesse in geld.",
    ],
    correctIndex: 0,
    explanationRu: "Запрос информации перед принятием решения — разумная и вежливая реакция.",
  },
  {
    id: "int-27",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед приглашает вас на встречу жителей района.",
    dialogue: ["Buurvrouw: Kom je ook naar de buurtbijeenkomst volgende week?"],
    options: [
      "Ja, leuk, hoe laat begint het?",
      "Nee, ik ken niemand in de buurt.",
      "Ik heb geen tijd voor buren.",
    ],
    correctIndex: 0,
    explanationRu: "Согласие с уточняющим вопросом — вовлечённая и вежливая реакция на приглашение.",
  },
  {
    id: "int-28",
    topic: "werk",
    level: "B1",
    situationRu: "Работодатель спрашивает про зарплатные ожидания.",
    dialogue: ["Werkgever: Wat voor salaris heeft u in gedachten?"],
    options: [
      "Dat hangt af van de functie, kunt u een indicatie geven?",
      "Zoveel mogelijk, natuurlijk.",
      "Dat gaat u niets aan.",
    ],
    correctIndex: 0,
    explanationRu: "Дипломатичный встречный вопрос — уместная тактика при обсуждении зарплаты на собеседовании.",
  },
  {
    id: "int-29",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы пришли за новым удостоверением, но забыли фото.",
    dialogue: ["Ambtenaar: Heeft u een pasfoto bij u?"],
    options: [
      "Nee, sorry, ik ben die vergeten. Kan ik later terugkomen?",
      "Nee, en dat is uw probleem.",
      "Ik heb nooit een foto nodig.",
    ],
    correctIndex: 0,
    explanationRu: "Извинение + предложение решения — конструктивная реакция на собственную ошибку.",
  },
  {
    id: "int-30",
    topic: "dagelijks_leven",
    level: "A2",
    situationRu: "Друг спрашивает, всё ли у вас в порядке после трудного дня.",
    dialogue: ["Vriend: Gaat het wel goed met je?"],
    options: [
      "Het gaat wel, het was een drukke dag.",
      "Waarom vraagt u dat, ik ken u niet.",
      "Dat is privé, praat er niet over.",
    ],
    correctIndex: 0,
    explanationRu: "Честный, но короткий ответ близкому знакомому — естественный регистр для дружеского разговора.",
  },
  {
    id: "int-31",
    topic: "wonen",
    level: "B1",
    situationRu: "Хозяин жилья предлагает продлить контракт аренды.",
    dialogue: ["Verhuurder: Wilt u het huurcontract verlengen?"],
    options: [
      "Ja, graag, onder dezelfde voorwaarden als nu?",
      "Ik weet het niet en het maakt mij niet uit.",
      "Nee, ik woon hier al te lang.",
    ],
    correctIndex: 0,
    explanationRu: "Согласие + уточнение условий — деловой и вежливый способ обсудить продление договора.",
  },

  // --- +100 batch: 10 scenarios per topic (huisarts, gemeente, werk,
  // winkel, buurt, school, bank, apotheek, station, verzekering), each
  // varying a concrete slot (day, item, city, reason) per instance for
  // genuine distinctness rather than copy-pasted repeats.
  {
    id: "int-gen-1",
    topic: "huisarts",
    level: "B1",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor maandag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik moet werken. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-2",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor dinsdag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik ben ziek. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-3",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor woensdag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik heb een andere afspraak. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-4",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor donderdag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want mijn kind is ziek. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-5",
    topic: "huisarts",
    level: "B1",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor vrijdag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik ben op vakantie. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-6",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor zaterdag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want de auto is kapot. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-7",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor zondag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik heb geen oppas. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-8",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor volgende week. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want het komt slecht uit. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-9",
    topic: "huisarts",
    level: "B1",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor morgenochtend. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik ben er niet. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-10",
    topic: "huisarts",
    level: "A2",
    situationRu: "Вы звоните в регистратуру, чтобы перенести приём у врача.",
    dialogue: ["Assistente: Goedemorgen, huisartsenpraktijk. Uw afspraak staat gepland voor vanmiddag. Komt dat nog uit?"],
    options: [
      "Nee, dat komt niet uit, want ik heb een sollicitatiegesprek. Kan het een andere dag?",
      "Ja, doet u maar wat u wilt.",
      "Ik weet het niet, vraagt u het aan iemand anders.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливо и по делу: сказать, что не подходит, назвать причину и попросить другой день.",
  },
  {
    id: "int-gen-11",
    topic: "gemeente",
    level: "B1",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het inschrijfformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het inschrijfformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-12",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het aanvraagformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het aanvraagformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-13",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het uittrekselformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het uittrekselformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-14",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het vergunningsformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het vergunningsformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-15",
    topic: "gemeente",
    level: "B1",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het verhuisformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het verhuisformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-16",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het belastingformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het belastingformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-17",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het kinderbijslagformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het kinderbijslagformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-18",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het paspoortformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het paspoortformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-19",
    topic: "gemeente",
    level: "B1",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het identiteitsformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het identiteitsformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-20",
    topic: "gemeente",
    level: "A2",
    situationRu: "Вы на приёме в муниципалитете, но не понимаете часть формуляра.",
    dialogue: ["Ambtenaar: Kunt u dit gedeelte van het adreswijzigingsformulier invullen?"],
    options: [
      "Sorry, ik begrijp dit gedeelte van het adreswijzigingsformulier niet helemaal. Kunt u het uitleggen?",
      "Nee, dat doe ik niet.",
      "Dat is niet mijn probleem.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливая просьба объяснить непонятную часть — уместная реакция, а не отказ или грубость.",
  },
  {
    id: "int-gen-21",
    topic: "werk",
    level: "B1",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je maandag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-22",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je dinsdag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-23",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je woensdag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-24",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je donderdag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-25",
    topic: "werk",
    level: "B1",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je vrijdag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-26",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je zaterdag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-27",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je zondag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-28",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je volgende week kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-29",
    topic: "werk",
    level: "B1",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je morgenochtend kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-30",
    topic: "werk",
    level: "A2",
    situationRu: "Ваш начальник спрашивает, можете ли вы поработать в выходной.",
    dialogue: ["Baas: Zou je vanmiddag kunnen werken? We hebben extra hulp nodig."],
    options: [
      "Dat is lastig, want ik heb al iets gepland. Kan iemand anders het doen?",
      "Nee, nooit.",
      "Ik luister niet naar u.",
    ],
    correctIndex: 0,
    explanationRu: "Вежливый отказ с объяснением и предложением альтернативы — более уместен, чем резкое 'нет'.",
  },
  {
    id: "int-gen-31",
    topic: "winkel",
    level: "B1",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze jas terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-32",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze schoenen terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-33",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag dit apparaat terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-34",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze broek terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-35",
    topic: "winkel",
    level: "B1",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag dit horloge terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-36",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze tas terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-37",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze trui terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-38",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze lamp terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-39",
    topic: "winkel",
    level: "B1",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag dit speelgoed terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-40",
    topic: "winkel",
    level: "A2",
    situationRu: "В магазине вы хотите вернуть товар, который не подошёл.",
    dialogue: ["Verkoper: Kan ik u helpen?"],
    options: [
      "Ja, ik wil graag deze fiets terugbrengen. Ik heb de bon nog.",
      "Nee, ik wil niets.",
      "Dit is een slechte winkel.",
    ],
    correctIndex: 0,
    explanationRu: "Ясно и вежливо объяснить цель визита — вернуть товар, показать чек.",
  },
  {
    id: "int-gen-41",
    topic: "buurt",
    level: "B1",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na tien uur 's avonds?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-42",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na elf uur 's avonds?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-43",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na middernacht?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-44",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na negen uur 's avonds?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-45",
    topic: "buurt",
    level: "B1",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na acht uur 's avonds?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-46",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na half elf 's avonds?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-47",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na tien uur?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-48",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na elf uur?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-49",
    topic: "buurt",
    level: "B1",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na twaalf uur 's nachts?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-50",
    topic: "buurt",
    level: "A2",
    situationRu: "Сосед жалуется на шум из вашей квартиры поздно вечером.",
    dialogue: ["Buurman: Kunt u wat rustiger zijn na negen uur?"],
    options: [
      "Sorry, dat wist ik niet. Ik zal er rekening mee houden.",
      "Bemoei u met uw eigen zaken.",
      "Ik doe wat ik wil in mijn eigen huis.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться и пообещать учесть просьбу — вежливая реакция на замечание соседа.",
  },
  {
    id: "int-gen-51",
    topic: "school",
    level: "B1",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was maandag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik moet werken. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-52",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was dinsdag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik ben ziek. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-53",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was woensdag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik heb een andere afspraak. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-54",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was donderdag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, mijn kind is ziek. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-55",
    topic: "school",
    level: "B1",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was vrijdag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik ben op vakantie. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-56",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was zaterdag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, de auto is kapot. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-57",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was zondag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik heb geen oppas. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-58",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was volgende week niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, het komt slecht uit. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-59",
    topic: "school",
    level: "B1",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was morgenochtend niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik ben er niet. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-60",
    topic: "school",
    level: "A2",
    situationRu: "Учитель вашего ребёнка спрашивает о его отсутствии в школе.",
    dialogue: ["Leraar: Uw kind was vanmiddag niet op school. Wat was er aan de hand?"],
    options: [
      "Het spijt me, ik heb een sollicitatiegesprek. Ik had het moeten doorgeven.",
      "Dat gaat u niets aan.",
      "Ik weet het niet, vraag het aan mijn kind.",
    ],
    correctIndex: 0,
    explanationRu: "Извиниться, кратко объяснить причину — уместная и ответственная реакция родителя.",
  },
  {
    id: "int-gen-61",
    topic: "bank",
    level: "B1",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een betaalrekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-62",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een spaarrekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-63",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een jongerenrekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-64",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een gezamenlijke rekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-65",
    topic: "bank",
    level: "B1",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een zakelijke rekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-66",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een tweede rekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-67",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een rekening voor mijn kind openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-68",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een nieuwe betaalrekening openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-69",
    topic: "bank",
    level: "B1",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een spaarrekening voor later openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-70",
    topic: "bank",
    level: "A2",
    situationRu: "В банке вы хотите открыть новый счёт.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen vandaag?"],
    options: [
      "Ik wil graag een rekening in euro's openen.",
      "Ik weet het niet.",
      "Geef mij gewoon geld.",
    ],
    correctIndex: 0,
    explanationRu: "Чётко сформулировать цель визита — открыть новый счёт.",
  },
  {
    id: "int-gen-71",
    topic: "apotheek",
    level: "B1",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn medicijnen ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-72",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn antibiotica ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-73",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn pijnstillers ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-74",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn hoestdrank ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-75",
    topic: "apotheek",
    level: "B1",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn zalf ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-76",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn tabletten ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-77",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn drupjes ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-78",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn recept voor mijn kind ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-79",
    topic: "apotheek",
    level: "B1",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn nieuwe medicijnen ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-80",
    topic: "apotheek",
    level: "A2",
    situationRu: "В аптеке вы хотите забрать лекарства по рецепту.",
    dialogue: ["Apotheker: Heeft u een recept van de huisarts?"],
    options: [
      "Ja, hier is mijn recept. Ik kom mijn herhaalrecept ophalen.",
      "Nee, geeft u mij maar wat.",
      "Ik heb geen tijd om te wachten.",
    ],
    correctIndex: 0,
    explanationRu: "Показать рецепт и объяснить цель визита — правильная, вежливая реакция.",
  },
  {
    id: "int-gen-81",
    topic: "station",
    level: "B1",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Utrecht gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-82",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Amsterdam gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-83",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Rotterdam gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-84",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Den Haag gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-85",
    topic: "station",
    level: "B1",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Eindhoven gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-86",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Groningen gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-87",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Arnhem gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-88",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Maastricht gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-89",
    topic: "station",
    level: "B1",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Tilburg gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-90",
    topic: "station",
    level: "A2",
    situationRu: "На вокзале вы пропустили поезд и спрашиваете о следующем.",
    dialogue: ["Medewerker: Waarmee kan ik u helpen?"],
    options: [
      "Ik heb mijn trein naar Breda gemist. Hoe laat vertrekt de volgende?",
      "Dat is uw schuld.",
      "Ik ga wel lopen.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно объяснить ситуацию и спросить о следующем поезде — уместная реакция.",
  },
  {
    id: "int-gen-91",
    topic: "verzekering",
    level: "B1",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de eigen bijdrage in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-92",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de dekking voor tandarts in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-93",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de premie in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-94",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de aanvullende verzekering in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-95",
    topic: "verzekering",
    level: "B1",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de vergoeding voor fysiotherapie in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-96",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over het eigen risico in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-97",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de dekking in het buitenland in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-98",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de opzegtermijn in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-99",
    topic: "verzekering",
    level: "B1",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de vergoeding voor medicijnen in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
  {
    id: "int-gen-100",
    topic: "verzekering",
    level: "A2",
    situationRu: "Вы звоните в страховую компанию по поводу неясного пункта в полисе.",
    dialogue: ["Medewerker: Waar kan ik u mee helpen?"],
    options: [
      "Ik heb een vraag over de vergoeding voor de bril in mijn polis. Dat is mij niet duidelijk.",
      "Uw bedrijf is slecht.",
      "Ik betaal toch niet.",
    ],
    correctIndex: 0,
    explanationRu: "Спокойно и по делу задать вопрос о непонятном пункте полиса.",
  },
];
