import { PracticeItem } from "../types";

// Seed task bank. Original items modelled on public exam blueprints (§7) —
// no reproduction of secure DUO/Cito material.
function base(overrides: Partial<PracticeItem>) {
  return {
    examTrack: "a2",
    cefrLevel: "A2",
    skill: "writing",
    register: "neutral",
    regionVariant: "netherlandic",
    l1ContrastFlag: true,
    singleListen: false,
    allowedTools: "none",
    timeLimitS: null,
    responseMinLen: null,
    difficultyTheta: 0,
    ...overrides,
  } as PracticeItem;
}

export const PRACTICE_ITEMS: PracticeItem[] = [
  base({
    id: "v2-mc-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Morgen ik ga naar de tandarts.", "Morgen ga ik naar de tandarts.", "Ik morgen ga naar de tandarts."],
    correctIndex: 1,
    explanationRu:
      "В нидерландском спрягаемый глагол всегда на втором месте (правило V2), даже если предложение начинается не с подлежащего. 'Morgen' занимает первое место → глагол 'ga' сразу после него.",
  } as PracticeItem),
  base({
    id: "sub-end-mc-1",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ik bel de huisarts, omdat ik ben ziek.",
      "Ik bel de huisarts, omdat ik ziek ben.",
      "Ik bel de huisarts, omdat ben ik ziek.",
    ],
    correctIndex: 1,
    explanationRu:
      "После omdat спрягаемый глагол уходит в конец придаточного предложения: 'omdat ik ziek ben', а не 'omdat ik ben ziek'.",
  } as PracticeItem),
  base({
    id: "sep-split-cloze-1",
    taskType: "cloze",
    topic: "dagelijks_leven",
    grammarTarget: "separable_verb",
    errorCodes: ["ERR_SEP_SPLIT"],
    textWithBlank: "Ik ___ mijn moeder morgen op. (opbellen)",
    answer: "bel",
    acceptableVariants: ["bel"],
    explanationRu:
      "Разделяемый глагол opbellen: приставка 'op' уходит в конец предложения, спрягается только основа: 'Ik bel ... op'.",
  } as PracticeItem),
  base({
    id: "aux-sel-mc-1",
    taskType: "mc",
    topic: "reizen",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb naar Utrecht gegaan.", "Ik ben naar Utrecht gegaan.", "Ik heb naar Utrecht ging."],
    correctIndex: 1,
    explanationRu:
      "Глаголы движения/изменения состояния (gaan, komen, worden) образуют перфект со вспомогательным zijn, а не hebben.",
  } as PracticeItem),
  base({
    id: "aspect-map-mc-1",
    taskType: "mc",
    topic: "verhaal",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    prompt: "Gisteren ___ ik een brief aan mijn moeder. (schrijven, voltooide actie)",
    options: ["schreef", "heb geschreven", "schrijf"],
    correctIndex: 1,
    explanationRu:
      "Внимание: это НЕ русский вид! 'heb geschreven' (perfectum) — завершённое единичное событие, о котором сообщается как о факте. 'schreef' (imperfectum) подошло бы для фона/повторяющегося действия. Не переводите по виду глагола в русском — определяйте по функции в контексте.",
  } as PracticeItem),
  base({
    id: "er-exist-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    prompt: "Kies de juiste zin.",
    options: ["In de tuin is een boom.", "Er staat een boom in de tuin.", "Een boom is er in de tuin."],
    correctIndex: 1,
    explanationRu:
      "Экзистенциальное 'er' используется, когда подлежащее неопределённое и стоит не в начале: 'Er staat een boom...'. Прямого аналога в русском нет.",
  } as PracticeItem),
  base({
    id: "er-quant-mc-1",
    taskType: "mc",
    topic: "boodschappen",
    grammarTarget: "er_quantitative",
    errorCodes: ["ERR_ER_QUANT"],
    prompt: "Heb je appels? Kies de juiste zin.",
    options: ["Ja, ik heb twee.", "Ja, ik heb er twee.", "Ja, ik heb ze er twee."],
    correctIndex: 1,
    explanationRu:
      "Количественное 'er' обязательно при ответе числом/количеством без существительного: 'Ik heb er twee' (= 'у меня их два').",
  } as PracticeItem),
  base({
    id: "er-prep-mc-1",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "er_prepositional",
    errorCodes: ["ERR_ER_PREP"],
    prompt: "Denk je aan de vergadering? Kies de juiste zin.",
    options: ["Ja, ik denk aan het.", "Ja, ik denk eraan.", "Ja, ik denk het aan."],
    correctIndex: 1,
    explanationRu:
      "Для неодушевлённых предметов после предлога используется 'er' + предлог слитно: 'eraan', а не 'aan het'.",
  } as PracticeItem),
  base({
    id: "er-loc-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "er_locative",
    errorCodes: ["ERR_ER_LOC"],
    prompt: "Woon je nog in Rotterdam? Kies de juiste zin.",
    options: ["Ja, ik woon er sinds 2020.", "Ja, ik woon in het sinds 2020.", "Ja, ik woon daar het sinds 2020."],
    correctIndex: 0,
    explanationRu: "Локативное 'er' заменяет уже упомянутое место вместо повторения названия города.",
  } as PracticeItem),
  base({
    id: "particle-mc-1",
    taskType: "mc",
    topic: "gesprek",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    skill: "speaking",
    prompt: "Kies de meest natuurlijke zin (vriend nodigt vriend uit).",
    options: ["Kom binnen.", "Kom maar binnen.", "Kom binnen, alsjeblieft, nu."],
    correctIndex: 1,
    explanationRu:
      "Частица 'maar' смягчает приглашение и звучит естественно в разговорной речи. В русском такой категории частиц почти нет — учите в контексте диалога, не переводите дословно.",
  } as PracticeItem),
  base({
    id: "art-dehet-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de huis", "het huis"],
    correctIndex: 1,
    explanationRu:
      "'huis' — het-слово. Надёжного правила нет (кроме уменьшительных на -je, которые всегда het) — het-слова запоминайте как меньший, отдельно заучиваемый набор.",
  } as PracticeItem),
  base({
    id: "adj-infl-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    prompt: "Kies de juiste zin.",
    options: ["een grote huis", "een groot huis"],
    correctIndex: 1,
    explanationRu:
      "Перед het-словом в неопределённой форме единственного числа прилагательное без окончания -e: 'een groot huis'. Учите это вместе с артиклем как единый блок.",
  } as PracticeItem),
  base({
    id: "cluster-mc-1",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "verb_cluster",
    errorCodes: ["ERR_CLUSTER"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ik had die brief moeten lezen eerder.",
      "Ik had die brief eerder lezen moeten.",
      "Ik had die brief eerder moeten lezen.",
    ],
    correctIndex: 2,
    explanationRu:
      "В группе глаголов в конце предложения (verb cluster) порядок фиксированный: 'moeten lezen', а не 'lezen moeten'. Прямого правила в русском нет — учите цепочку целиком.",
  } as PracticeItem),
  base({
    id: "sep-part-mc-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "separable_verb_participle",
    errorCodes: ["ERR_SEP_PART"],
    prompt: "Kies de juiste zin (voltooid deelwoord van 'opbellen').",
    options: ["Ik heb mijn moeder geopbeld.", "Ik heb mijn moeder opgebeld.", "Ik heb mijn moeder gebeldop."],
    correctIndex: 1,
    explanationRu:
      "У разделяемых глаголов приставка 'ge-' вставляется между приставкой и основой: op + ge + beld = 'opgebeld', а не 'geopbeld'.",
  } as PracticeItem),
  base({
    id: "neg-pos-mc-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Ik niet begrijp het formulier.", "Ik begrijp het formulier niet.", "Ik begrijp niet het formulier."],
    correctIndex: 1,
    explanationRu:
      "'niet' обычно стоит в конце предложения или перед тем, что отрицается, но не сразу перед личным глаголом. Здесь 'niet' идёт после дополнения 'het formulier'.",
  } as PracticeItem),
  base({
    id: "plur-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    prompt: "Kies het juiste meervoud van 'huis'.",
    options: ["huisen", "huizen", "huissen"],
    correctIndex: 1,
    explanationRu:
      "Множественное число 'huis' образуется с изменением s→z и окончанием -en: 'huizen'. Выбор -en/-s не всегда предсказуем — запоминайте форму вместе со словом (см. раздел «Словарь»).",
  } as PracticeItem),
  base({
    id: "dim-art-mc-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "diminutive_article",
    errorCodes: ["ERR_DIM_ART"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de huisje", "het huisje"],
    correctIndex: 1,
    explanationRu:
      "Все уменьшительные формы на -je берут артикль het, даже если исходное слово — de-слово ('de afspraak' → 'het afspraakje'). Это одно из немногих надёжных правил артиклей.",
  } as PracticeItem),
  base({
    id: "prep-fixed-mc-1",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies de juiste zin.",
    options: ["Ik wacht voor de huisarts.", "Ik wacht op de huisarts.", "Ik wacht bij de huisarts."],
    correctIndex: 1,
    explanationRu:
      "'wachten op' — устойчивый предлог (vast voorzetsel), его нельзя вывести логически из значения. Учите такие сочетания как готовый блок, а не переводите по смыслу.",
  } as PracticeItem),
  base({
    id: "colloc-mc-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    prompt: "Kies de juiste zin.",
    options: ["Ik doe een afspraak.", "Ik maak een afspraak.", "Ik neem een afspraak."],
    correctIndex: 1,
    explanationRu:
      "Устойчивое сочетание — 'een afspraak maken' (буквально «делать» в смысле 'maken'), а не 'doen' или 'nemen'. Это коллокация, а не свободное сочетание слов.",
  } as PracticeItem),
  base({
    id: "v2-mc-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Volgende week ik begin met mijn nieuwe baan.", "Volgende week begin ik met mijn nieuwe baan.", "Ik volgende week begin met mijn nieuwe baan."],
    correctIndex: 1,
    explanationRu:
      "Снова правило V2: 'volgende week' на первом месте → глагол 'begin' сразу после него, на втором месте.",
  } as PracticeItem),
  base({
    id: "aux-sel-mc-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb ziek geworden.", "Ik ben ziek geworden.", "Ik heb ziek geweest geworden."],
    correctIndex: 1,
    explanationRu:
      "'worden' (изменение состояния) тоже образует перфект с zijn: 'ben geworden', а не 'heb geworden'.",
  } as PracticeItem),
  base({
    id: "aspect-map-mc-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    prompt: "Toen ik klein was, ___ ik elke zomer bij mijn oma. (wonen, herhaalde/achtergrond-situatie)",
    options: ["heb gewoond", "woonde", "woon"],
    correctIndex: 1,
    explanationRu:
      "Здесь imperfectum ('woonde'), потому что это фон/повторяющаяся ситуация в прошлом, а не единичное завершённое событие. Снова: ориентируйтесь на функцию, а не на русский вид.",
  } as PracticeItem),
  base({
    id: "particle-mc-2",
    taskType: "mc",
    topic: "gesprek",
    skill: "speaking",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    prompt: "Kies de meest natuurlijke zin (je stelt een klein verzoek aan een collega).",
    options: ["Kun je dat even voor mij doen?", "Kun je dat voor mij doen?", "Doe dat voor mij, nu."],
    correctIndex: 0,
    explanationRu:
      "Частица 'even' смягчает просьбу и делает её более естественной и менее требовательной — типичное употребление в разговорной речи.",
  } as PracticeItem),
  base({
    id: "er-exist-mc-2",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    prompt: "Kies de juiste zin.",
    options: ["In de buurt is een school.", "Er is een school in de buurt.", "Een school is er in de buurt."],
    correctIndex: 1,
    explanationRu: "Ещё один пример экзистенциального 'er': неопределённое подлежащее 'een school' требует 'er' в начале.",
  } as PracticeItem),
  base({
    id: "phon-vlength-mc-1",
    taskType: "mc",
    topic: "phonology",
    grammarTarget: "vowel_length",
    errorCodes: ["ERR_PHON_VLENGTH"],
    prompt: "Kies het juiste woord: 'Vannacht was er een volle ___ aan de hemel.' (луна)",
    options: ["man", "maan"],
    correctIndex: 1,
    explanationRu:
      "'maan' (луна) с долгим гласным [aː], 'man' (мужчина) с коротким [ɑ]. В русском долгота гласных не различает слова — уделите этому отдельное внимание, желательно на слух в разделе «Говорение».",
  } as PracticeItem),
  base({
    id: "phon-frontround-mc-1",
    taskType: "mc",
    topic: "phonology",
    grammarTarget: "front_rounded_vowels",
    errorCodes: ["ERR_PHON_FRONTROUND"],
    prompt: "Kies het juiste woord: 'Ik kan je niet goed ___.' (слышать)",
    options: ["horen", "huren"],
    correctIndex: 0,
    explanationRu:
      "'horen' (слышать) vs 'huren' (снимать/арендовать) — разные огублённые гласные. В русском таких гласных нет, поэтому пара звучит обманчиво похоже для новичка.",
  } as PracticeItem),
  base({
    id: "phon-devoice-mc-1",
    taskType: "mc",
    topic: "phonology",
    grammarTarget: "final_devoicing",
    errorCodes: ["ERR_PHON_DEVOICE"],
    prompt: "Kies de juiste spelling van het meervoud van 'hond'.",
    options: ["honten", "honden"],
    correctIndex: 1,
    explanationRu:
      "В конце слова 'hond' звучит оглушённо, почти как /t/, но пишется по основе множественного числа: 'honden'. Не пишите так, как слышите на конце слова.",
  } as PracticeItem),
  base({
    id: "phon-xg-mc-1",
    taskType: "mc",
    topic: "phonology",
    grammarTarget: "x_g_contrast",
    errorCodes: ["ERR_PHON_XG"],
    prompt: "Welke klank hoor je aan het begin van 'geel' (жёлтый)?",
    options: ["Звонкий /ɣ/, как в 'geel'", "Глухой /x/, как в 'acht'"],
    correctIndex: 0,
    explanationRu:
      "В начале слова 'g' обычно звонкая /ɣ/, а сочетание 'ch' — глухая /x/. Обе отличаются от русского [х] — приоритетная пара для тренировки произношения (см. раздел «Говорение»).",
  } as PracticeItem),
  base({
    id: "prep-fixed-mc-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies de juiste zin.",
    options: ["Ik hou van muziek.", "Ik hou aan muziek.", "Ik hou op muziek."],
    correctIndex: 0,
    explanationRu:
      "'houden van' — устойчивый предлог для 'любить что-то'. Ещё один пример vast voorzetsel, который нужно запоминать целиком.",
  } as PracticeItem),
  base({
    id: "sentence-transform-1",
    taskType: "sentence_transform",
    topic: "gezondheid",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Combineer de zinnen met 'omdat'.",
    source: "Ik ga naar de huisarts. Ik ben ziek.",
    answer: "Ik ga naar de huisarts, omdat ik ziek ben.",
    explanationRu: "После 'omdat' спрягаемый глагол в самом конце придаточного.",
  } as PracticeItem),
  base({
    id: "short-write-1",
    taskType: "short_write",
    skill: "writing",
    examTrack: "staatsexamen_p1",
    cefrLevel: "B1",
    topic: "afspraak_verzetten",
    grammarTarget: undefined,
    errorCodes: ["ERR_SUB_END", "ERR_V2_POS", "ERR_AUX_SEL"],
    responseMinLen: 30,
    timeLimitS: 600,
    taskPrompt:
      "Schrijf een e-mail aan de gemeente. Je wilt je afspraak van volgende week verzetten naar een andere dag. Leg kort uit waarom.",
    requirements: [
      "vraagt om de afspraak te verzetten",
      "geeft een reden",
      "stelt een nieuwe datum of vraagt om opties",
      "beleefde aanhef en afsluiting",
    ],
    modelAnswer:
      "Beste meneer/mevrouw,\n\nIk heb volgende week een afspraak bij de gemeente, maar ik kan helaas niet komen omdat ik moet werken. Kunt u mij een andere datum geven, bijvoorbeeld de week erna?\n\nAlvast bedankt.\n\nMet vriendelijke groet,",
  } as PracticeItem),

  // --- +100 batch: ~4-5 new items per existing grammarTarget, mixing mc/
  // cloze/sentence_transform, so FSRS review data accumulates across the
  // full grammar-point set rather than just the seed items.
  base({
    id: "v2-gen-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Vandaag ik werk thuis.", "Vandaag werk ik thuis.", "Ik vandaag werk thuis."],
    correctIndex: 1,
    explanationRu:
      "Правило V2: спрягаемый глагол всегда на втором месте. 'Vandaag' занимает первое место, поэтому 'werk' сразу следует за ним.",
  } as PracticeItem),
  base({
    id: "v2-gen-2",
    taskType: "mc",
    topic: "vervoer",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Straks ga ik naar de markt.", "Straks ik ga naar de markt.", "Ik straks ga naar de markt."],
    correctIndex: 0,
    explanationRu:
      "После 'straks' на первом месте сразу идёт спрягаемый глагол 'ga', а не подлежащее.",
  } as PracticeItem),
  base({
    id: "v2-gen-3",
    taskType: "cloze",
    topic: "gezondheid",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    textWithBlank: "Morgen ___ ik naar de tandarts. (gaan)",
    answer: "ga",
    acceptableVariants: ["ga"],
    explanationRu:
      "Наречие 'morgen' стоит на первом месте, поэтому спрягаемый глагол 'ga' идёт вторым, перед подлежащим 'ik'.",
  } as PracticeItem),
  base({
    id: "v2-gen-4",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Elke dag drink ik koffie.", "Elke dag ik drink koffie.", "Ik elke dag drink koffie."],
    correctIndex: 0,
    explanationRu:
      "'Elke dag' открывает предложение, значит глагол 'drink' сразу занимает второе место.",
  } as PracticeItem),
  base({
    id: "v2-gen-5",
    taskType: "sentence_transform",
    topic: "werk",
    grammarTarget: "V2",
    errorCodes: ["ERR_V2_POS"],
    prompt: "Begin de zin met 'Volgende week'.",
    source: "Ik begin volgende week met mijn nieuwe baan.",
    answer: "Volgende week begin ik met mijn nieuwe baan.",
    explanationRu:
      "Когда 'volgende week' выносится в начало, глагол 'begin' остаётся на втором месте, а подлежащее 'ik' сдвигается после него.",
  } as PracticeItem),

  base({
    id: "sub-end-gen-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ik denk dat hij morgen komt.",
      "Ik denk dat hij komt morgen.",
      "Ik denk dat komt hij morgen.",
    ],
    correctIndex: 0,
    explanationRu: "После 'dat' спрягаемый глагол уходит в конец придаточного: 'dat hij morgen komt'.",
  } as PracticeItem),
  base({
    id: "sub-end-gen-2",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ze blijft thuis, omdat ze moe is.",
      "Ze blijft thuis, omdat is ze moe.",
      "Ze blijft thuis, omdat ze is moe.",
    ],
    correctIndex: 0,
    explanationRu: "'Omdat' требует, чтобы глагол 'is' стоял в самом конце придаточного предложения.",
  } as PracticeItem),
  base({
    id: "sub-end-gen-3",
    taskType: "cloze",
    topic: "werk",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    textWithBlank: "Ik weet niet of hij vandaag ___. (werken)",
    answer: "werkt",
    acceptableVariants: ["werkt"],
    explanationRu: "После 'of' глагол 'werkt' стоит в конце придаточного предложения.",
  } as PracticeItem),
  base({
    id: "sub-end-gen-4",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Kies de juiste zin.",
    options: [
      "Als het regent, ik blijf thuis.",
      "Als het regent, blijf ik thuis.",
      "Als regent het, blijf ik thuis.",
    ],
    correctIndex: 1,
    explanationRu:
      "'Als het regent' — придаточное с глаголом в конце ('regent'); в главном предложении, идущем после запятой, — инверсия ('blijf ik').",
  } as PracticeItem),
  base({
    id: "sub-end-gen-5",
    taskType: "sentence_transform",
    topic: "dagelijks_leven",
    grammarTarget: "subordinate_clause",
    errorCodes: ["ERR_SUB_END"],
    prompt: "Combineer de zinnen met 'terwijl'.",
    source: "Ik kook. Mijn man dekt de tafel.",
    answer: "Ik kook, terwijl mijn man de tafel dekt.",
    explanationRu: "После 'terwijl' спрягаемый глагол 'dekt' уходит в конец придаточного предложения.",
  } as PracticeItem),

  base({
    id: "sep-split-gen-1",
    taskType: "cloze",
    topic: "dagelijks_leven",
    grammarTarget: "separable_verb",
    errorCodes: ["ERR_SEP_SPLIT"],
    textWithBlank: "Ik ___ de tv aan om acht uur. (aanzetten)",
    answer: "zet",
    acceptableVariants: ["zet"],
    explanationRu: "Разделяемый глагол 'aanzetten': основа 'zet' спрягается, приставка 'aan' уходит в конец.",
  } as PracticeItem),
  base({
    id: "sep-split-gen-2",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "separable_verb",
    errorCodes: ["ERR_SEP_SPLIT"],
    prompt: "Kies de juiste zin.",
    options: ["Ik ruim mijn kamer op.", "Ik opruim mijn kamer.", "Ik ruim op mijn kamer."],
    correctIndex: 0,
    explanationRu: "'Opruimen': приставка 'op' идёт в конец предложения, а не перед дополнением.",
  } as PracticeItem),
  base({
    id: "sep-split-gen-3",
    taskType: "cloze",
    topic: "dagelijks_leven",
    grammarTarget: "separable_verb",
    errorCodes: ["ERR_SEP_SPLIT"],
    textWithBlank: "Zij ___ vroeg op. (opstaan)",
    answer: "staat",
    acceptableVariants: ["staat"],
    explanationRu: "'Opstaan': основа 'staat' спрягается, приставка 'op' остаётся в конце предложения.",
  } as PracticeItem),
  base({
    id: "sep-split-gen-4",
    taskType: "mc",
    topic: "familie",
    grammarTarget: "separable_verb",
    errorCodes: ["ERR_SEP_SPLIT"],
    prompt: "Kies de juiste zin.",
    options: ["Hij belt zijn moeder op.", "Hij opbelt zijn moeder.", "Hij belt op zijn moeder."],
    correctIndex: 0,
    explanationRu: "'Opbellen' в главном предложении разделяется: 'belt ... op' — приставка в самом конце.",
  } as PracticeItem),

  base({
    id: "aux-sel-gen-1",
    taskType: "mc",
    topic: "vervoer",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb naar de winkel gelopen.", "Ik ben naar de winkel gelopen.", "Ik ben naar de winkel gehad."],
    correctIndex: 1,
    explanationRu: "'Lopen' с указанием направления передаёт перемещение — перфект образуется с 'zijn'.",
  } as PracticeItem),
  base({
    id: "aux-sel-gen-2",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    prompt: "Kies de juiste zin.",
    options: ["Zij heeft het boek gelezen.", "Zij is het boek gelezen.", "Zij heeft het boek geleesd."],
    correctIndex: 0,
    explanationRu: "'Lezen' — переходный глагол без изменения места/состояния, перфект образуется с 'hebben'.",
  } as PracticeItem),
  base({
    id: "aux-sel-gen-3",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    prompt: "Kies de juiste zin.",
    options: ["Wij zijn vroeg opgestaan.", "Wij hebben vroeg opgestaan.", "Wij zijn vroeg opgestaand."],
    correctIndex: 0,
    explanationRu: "'Opstaan' обозначает изменение состояния (встать), перфект образуется с 'zijn'.",
  } as PracticeItem),
  base({
    id: "aux-sel-gen-4",
    taskType: "cloze",
    topic: "gezondheid",
    grammarTarget: "hebben_zijn",
    errorCodes: ["ERR_AUX_SEL"],
    textWithBlank: "Hij ___ gisteren ziek geweest. (zijn)",
    answer: "is",
    acceptableVariants: ["is"],
    explanationRu: "'Zijn' в перфекте от 'zijn' (быть) образуется с 'is' — 'is geweest'.",
  } as PracticeItem),

  base({
    id: "aspect-map-gen-1",
    taskType: "mc",
    topic: "verhaal",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    prompt: "Vroeger ___ ik elke dag voetbal. (spelen, gewoonte in het verleden)",
    options: ["speelde", "heb gespeeld", "speel"],
    correctIndex: 0,
    explanationRu: "Привычное повторяющееся действие в прошлом ('раньше я играл каждый день') — imperfectum.",
  } as PracticeItem),
  base({
    id: "aspect-map-gen-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    prompt: "Ik ___ dat boek al. (lezen, voltooide actie, spreektaal)",
    options: ["las", "heb gelezen", "heb gelesen"],
    correctIndex: 1,
    explanationRu: "Одиночное завершённое действие с результатом в настоящем ('я уже прочитал') — perfectum в разговорной речи.",
  } as PracticeItem),
  base({
    id: "aspect-map-gen-3",
    taskType: "cloze",
    topic: "verhaal",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    textWithBlank: "Vorig jaar ___ ik in Spanje. (wonen)",
    answer: "woonde",
    acceptableVariants: ["woonde"],
    explanationRu: "Длительное состояние в прошлом ('в прошлом году я жил') — imperfectum.",
  } as PracticeItem),
  base({
    id: "aspect-map-gen-4",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "imperfectum_perfectum",
    errorCodes: ["ERR_ASPECT_MAP"],
    prompt: "Gisteren ___ ik mijn nieuwe collega. (ontmoeten, eenmalige actie)",
    options: ["ontmoette", "heb ontmoet", "ontmoet"],
    correctIndex: 1,
    explanationRu: "Однократное завершённое событие вчера, о котором сообщается как о новости — perfectum.",
  } as PracticeItem),

  base({
    id: "er-exist-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    prompt: "Kies de juiste zin.",
    options: ["Er staat een kast in de kamer.", "Staat een kast in de kamer.", "Een kast staat er in de kamer."],
    correctIndex: 0,
    explanationRu: "Экзистенциальное 'er' обязательно, когда подлежащее неопределённое и стоит не в начале предложения.",
  } as PracticeItem),
  base({
    id: "er-exist-gen-2",
    taskType: "cloze",
    topic: "buurt",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    textWithBlank: "___ is een winkel om de hoek. (er)",
    answer: "Er",
    acceptableVariants: ["Er"],
    explanationRu: "'Er is een winkel' — вводное 'er' перед неопределённым подлежащим 'een winkel'.",
  } as PracticeItem),
  base({
    id: "er-exist-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    prompt: "Kies de juiste zin.",
    options: ["Er wachten twee mensen bij de balie.", "Wachten twee mensen bij de balie.", "Twee mensen er wachten bij de balie."],
    correctIndex: 0,
    explanationRu: "Неопределённое множественное подлежащее 'twee mensen' требует вводного 'er' в начале.",
  } as PracticeItem),
  base({
    id: "er-exist-gen-4",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "er_existential",
    errorCodes: ["ERR_ER_EXIST"],
    prompt: "Kies de juiste zin.",
    options: ["Er zit een fout in het formulier.", "Zit een fout in het formulier.", "Een fout zit er in het formulier."],
    correctIndex: 0,
    explanationRu: "'Er zit een fout' — стандартная конструкция с экзистенциальным 'er' для неопределённого подлежащего.",
  } as PracticeItem),

  base({
    id: "er-quant-gen-1",
    taskType: "mc",
    topic: "familie",
    grammarTarget: "er_quantitative",
    errorCodes: ["ERR_ER_QUANT"],
    prompt: "Hoeveel kinderen heb je? Ik heb ___ twee.",
    options: ["er", "het", "die"],
    correctIndex: 0,
    explanationRu: "Количественное 'er' обязательно перед числительным без существительного: 'Ik heb er twee'.",
  } as PracticeItem),
  base({
    id: "er-quant-gen-2",
    taskType: "cloze",
    topic: "dagelijks_leven",
    grammarTarget: "er_quantitative",
    errorCodes: ["ERR_ER_QUANT"],
    textWithBlank: "Heb je broodjes? Ja, ik heb ___ vijf. (er)",
    answer: "er",
    acceptableVariants: ["er"],
    explanationRu: "После числительного без существительного нужно вводное 'er': 'ik heb er vijf'.",
  } as PracticeItem),
  base({
    id: "er-quant-gen-3",
    taskType: "mc",
    topic: "geld",
    grammarTarget: "er_quantitative",
    errorCodes: ["ERR_ER_QUANT"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb er drie.", "Ik heb drie.", "Ik heb het drie."],
    correctIndex: 0,
    explanationRu: "Когда существительное опущено, а осталось только числительное, перед ним ставится 'er'.",
  } as PracticeItem),
  base({
    id: "er-quant-gen-4",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "er_quantitative",
    errorCodes: ["ERR_ER_QUANT"],
    prompt: "Hoeveel collega's heb je? Ik heb ___ veel.",
    options: ["er", "die", "ze"],
    correctIndex: 0,
    explanationRu: "'Er' используется и с наречиями количества ('veel', 'weinig') без прямого существительного.",
  } as PracticeItem),

  base({
    id: "er-prep-gen-1",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "er_prepositional",
    errorCodes: ["ERR_ER_PREP"],
    prompt: "Kies de juiste zin.",
    options: ["Ik denk er vaak aan.", "Ik denk vaak aan het.", "Ik denk vaak aan er."],
    correctIndex: 0,
    explanationRu: "Предложное 'er' заменяет неодушевлённый объект: 'eraan denken' → 'er ... aan denken'.",
  } as PracticeItem),
  base({
    id: "er-prep-gen-2",
    taskType: "cloze",
    topic: "dagelijks_leven",
    grammarTarget: "er_prepositional",
    errorCodes: ["ERR_ER_PREP"],
    textWithBlank: "Ik ben ___ blij mee. (er)",
    answer: "er",
    acceptableVariants: ["er"],
    explanationRu: "'Ergens blij mee zijn' → 'er ... mee zijn' для неодушевлённого объекта.",
  } as PracticeItem),
  base({
    id: "er-prep-gen-3",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "er_prepositional",
    errorCodes: ["ERR_ER_PREP"],
    prompt: "Kies de juiste zin.",
    options: ["Ik wacht er nog op.", "Ik wacht nog op het.", "Ik wacht op er nog."],
    correctIndex: 0,
    explanationRu: "'Wachten op iets' → предложное 'er' заменяет 'het': 'er ... op wachten'.",
  } as PracticeItem),
  base({
    id: "er-prep-gen-4",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "er_prepositional",
    errorCodes: ["ERR_ER_PREP"],
    prompt: "Kies de juiste zin.",
    options: ["Ik ben er niet bang voor.", "Ik ben niet bang voor het.", "Ik ben bang voor er niet."],
    correctIndex: 0,
    explanationRu: "'Bang zijn voor iets' → 'er ... voor' заменяет неодушевлённое дополнение.",
  } as PracticeItem),

  base({
    id: "er-loc-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "er_locative",
    errorCodes: ["ERR_ER_LOC"],
    prompt: "Woon je nog in Utrecht? Ja, ik woon ___ nog.",
    options: ["er", "daar", "het"],
    correctIndex: 0,
    explanationRu: "Локативное 'er' заменяет ранее упомянутое место в безударной позиции: 'ik woon er nog'.",
  } as PracticeItem),
  base({
    id: "er-loc-gen-2",
    taskType: "cloze",
    topic: "werk",
    grammarTarget: "er_locative",
    errorCodes: ["ERR_ER_LOC"],
    textWithBlank: "Ik werk ___ al vijf jaar. (er)",
    answer: "er",
    acceptableVariants: ["er"],
    explanationRu: "Место работы, уже упомянутое ранее, заменяется безударным 'er'.",
  } as PracticeItem),
  base({
    id: "er-loc-gen-3",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "er_locative",
    errorCodes: ["ERR_ER_LOC"],
    prompt: "Kies de juiste zin.",
    options: ["Ik ben er nog nooit geweest.", "Ik ben daar nog nooit er geweest.", "Ik ben nooit geweest er."],
    correctIndex: 0,
    explanationRu: "'Er' стоит сразу после спрягаемого глагола, заменяя ранее упомянутое место.",
  } as PracticeItem),
  base({
    id: "er-loc-gen-4",
    taskType: "mc",
    topic: "buurt",
    grammarTarget: "er_locative",
    errorCodes: ["ERR_ER_LOC"],
    prompt: "Kies de juiste zin.",
    options: ["Zij komt er net vandaan.", "Zij komt daar net er vandaan.", "Zij komt vandaan er net."],
    correctIndex: 0,
    explanationRu: "'Er ... vandaan' — стандартная локативная конструкция для 'оттуда'.",
  } as PracticeItem),

  base({
    id: "particle-gen-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    prompt: "Kies de beste zin (vriendelijk verzoek).",
    options: ["Kunt u mij helpen?", "Kunt u mij even helpen?", "Kunt u mij helpen nu?"],
    correctIndex: 1,
    explanationRu: "Модальная частица 'even' смягчает просьбу и звучит более вежливо/естественно.",
  } as PracticeItem),
  base({
    id: "particle-gen-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    prompt: "Kies de beste zin (aanmoediging).",
    options: ["Kom binnen.", "Kom maar binnen.", "Kom nu binnen."],
    correctIndex: 1,
    explanationRu: "'Maar' здесь смягчает приглашение, делает его более дружелюбным, а не приказным.",
  } as PracticeItem),
  base({
    id: "particle-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    prompt: "Kies de beste zin (verbazing).",
    options: ["Wat doe je hier?", "Wat doe je hier toch?", "Wat doe je hier gewoon?"],
    correctIndex: 1,
    explanationRu: "'Toch' в вопросе выражает лёгкое удивление, характерную для разговорной речи частицу.",
  } as PracticeItem),
  base({
    id: "particle-gen-4",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "modal_particle",
    errorCodes: ["ERR_PARTICLE"],
    prompt: "Kies de beste zin (geruststelling).",
    options: ["Het komt goed.", "Het komt wel goed.", "Het komt zeker goed."],
    correctIndex: 1,
    explanationRu: "'Wel' смягчает утверждение и звучит как естественное успокоение, типичное для разговорной речи.",
  } as PracticeItem),

  base({
    id: "art-dehet-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de raam", "het raam", "een raam die"],
    correctIndex: 1,
    explanationRu: "'Raam' (окно) — het-слово; артикль 'het raam'.",
  } as PracticeItem),
  base({
    id: "art-dehet-gen-2",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de medicijn", "het medicijn", "een medicijn deze"],
    correctIndex: 1,
    explanationRu: "'Medicijn' (лекарство) — het-слово; артикль 'het medicijn'.",
  } as PracticeItem),
  base({
    id: "art-dehet-gen-3",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["het contract", "de contract", "een contract die"],
    correctIndex: 0,
    explanationRu: "'Contract' — het-слово; артикль 'het contract'.",
  } as PracticeItem),
  base({
    id: "art-dehet-gen-4",
    taskType: "mc",
    topic: "gemeente",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de formulier", "het formulier", "een formulier deze"],
    correctIndex: 1,
    explanationRu: "'Formulier' — het-слово; артикль 'het formulier'.",
  } as PracticeItem),
  base({
    id: "art-dehet-gen-5",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "de_het",
    errorCodes: ["ERR_ART_DEHET"],
    prompt: "Kies het juiste lidwoord.",
    options: ["het sleutel", "de sleutel", "een sleutel dat"],
    correctIndex: 1,
    explanationRu: "'Sleutel' (ключ) — de-слово; артикль 'de sleutel'.",
  } as PracticeItem),

  base({
    id: "adj-infl-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    prompt: "Kies de juiste zin.",
    options: ["een groot huis", "een grote huis", "het groot huis"],
    correctIndex: 0,
    explanationRu: "Перед het-словом в неопределённой форме единственного числа прилагательное без -e: 'een groot huis'.",
  } as PracticeItem),
  base({
    id: "adj-infl-gen-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    prompt: "Kies de juiste zin.",
    options: ["de nieuwe auto", "de nieuw auto", "een nieuw de auto"],
    correctIndex: 0,
    explanationRu: "Перед de-словом (и в определённой форме перед het-словом) прилагательное всегда с -e: 'de nieuwe auto'.",
  } as PracticeItem),
  base({
    id: "adj-infl-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    prompt: "Kies de juiste zin.",
    options: ["het grote ziekenhuis", "het groot ziekenhuis", "de grote ziekenhuis"],
    correctIndex: 0,
    explanationRu: "С определённым артиклем 'het' прилагательное всегда получает -e: 'het grote ziekenhuis'.",
  } as PracticeItem),
  base({
    id: "adj-infl-gen-4",
    taskType: "cloze",
    topic: "werk",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    textWithBlank: "Ik heb een ___ contract. (vast)",
    answer: "vast",
    acceptableVariants: ["vast"],
    explanationRu: "Перед het-словом ('contract') в неопределённой форме прилагательное без -e: 'een vast contract'.",
  } as PracticeItem),
  base({
    id: "adj-infl-gen-5",
    taskType: "mc",
    topic: "familie",
    grammarTarget: "adjective_inflection",
    errorCodes: ["ERR_ADJ_INFL"],
    prompt: "Kies de juiste zin.",
    options: ["mijn oudere broer", "mijn ouder broer", "mijn oud broer"],
    correctIndex: 0,
    explanationRu: "После bezitten (bezittelijk voornaamwoord) 'mijn' прилагательное перед de-словом получает -e: 'oudere broer'.",
  } as PracticeItem),

  base({
    id: "cluster-gen-1",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "verb_cluster",
    errorCodes: ["ERR_CLUSTER"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ik heb het rapport moeten schrijven.",
      "Ik heb moeten het rapport schrijven.",
      "Ik moeten het rapport heb schrijven.",
    ],
    correctIndex: 0,
    explanationRu: "В кластере глаголов в конце: сначала объект, потом 'moeten schrijven' (модальный + инфинитив).",
  } as PracticeItem),
  base({
    id: "cluster-gen-2",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "verb_cluster",
    errorCodes: ["ERR_CLUSTER"],
    prompt: "Kies de juiste zin.",
    options: [
      "Ik zal het morgen afmaken.",
      "Ik zal afmaken het morgen.",
      "Ik het morgen zal afmaken.",
    ],
    correctIndex: 0,
    explanationRu: "'Zal' (спрягаемый глагол) на втором месте, инфинитив 'afmaken' — в конце предложения.",
  } as PracticeItem),
  base({
    id: "cluster-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "verb_cluster",
    errorCodes: ["ERR_CLUSTER"],
    prompt: "Kies de juiste zin.",
    options: [
      "Zij had een afspraak willen maken.",
      "Zij had willen een afspraak maken.",
      "Zij een afspraak had willen maken.",
    ],
    correctIndex: 0,
    explanationRu: "Кластер из трёх глаголов в конце: объект перед кластером, затем 'willen maken'.",
  } as PracticeItem),
  base({
    id: "cluster-gen-4",
    taskType: "sentence_transform",
    topic: "werk",
    grammarTarget: "verb_cluster",
    errorCodes: ["ERR_CLUSTER"],
    prompt: "Maak de zin af met 'kunnen'.",
    source: "Ik wil dit vandaag afmaken.",
    answer: "Ik wil dit vandaag kunnen afmaken.",
    explanationRu: "Дополнительный модальный глагол 'kunnen' вставляется перед инфинитивом в конце кластера.",
  } as PracticeItem),

  base({
    id: "sep-part-gen-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "separable_verb_participle",
    errorCodes: ["ERR_SEP_PART"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb de tv aangezet.", "Ik heb aangezet de tv.", "Ik heb de tv gezetaan."],
    correctIndex: 0,
    explanationRu: "В причастии разделяемого глагола 'ge-' встаёт между приставкой и основой: 'aan-ge-zet'.",
  } as PracticeItem),
  base({
    id: "sep-part-gen-2",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "separable_verb_participle",
    errorCodes: ["ERR_SEP_PART"],
    prompt: "Kies de juiste zin.",
    options: ["Ik heb mijn kamer opgeruimd.", "Ik heb mijn kamer geopruimd.", "Ik heb opgeruimd mijn kamer."],
    correctIndex: 0,
    explanationRu: "'Opruimen' → причастие 'opgeruimd' — 'ge-' между 'op' и основой 'ruim'.",
  } as PracticeItem),
  base({
    id: "sep-part-gen-3",
    taskType: "cloze",
    topic: "familie",
    grammarTarget: "separable_verb_participle",
    errorCodes: ["ERR_SEP_PART"],
    textWithBlank: "Ik heb mijn moeder net ___. (opbellen)",
    answer: "opgebeld",
    acceptableVariants: ["opgebeld"],
    explanationRu: "'Opbellen' → причастие 'opgebeld', 'ge-' стоит после приставки 'op'.",
  } as PracticeItem),
  base({
    id: "sep-part-gen-4",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "separable_verb_participle",
    errorCodes: ["ERR_SEP_PART"],
    prompt: "Kies de juiste zin.",
    options: ["Zij heeft het formulier ingevuld.", "Zij heeft het formulier geinvuld.", "Zij heeft ingevuld het formulier."],
    correctIndex: 0,
    explanationRu: "'Invullen' → причастие 'ingevuld' — 'ge-' между приставкой 'in' и основой 'vuld'.",
  } as PracticeItem),

  base({
    id: "neg-pos-gen-1",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Ik ga niet naar de markt.", "Ik ga naar de markt niet.", "Ik niet ga naar de markt."],
    correctIndex: 0,
    explanationRu: "'Niet' обычно стоит перед предложной группой места ('naar de markt'), а не в конце.",
  } as PracticeItem),
  base({
    id: "neg-pos-gen-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Ik werk niet vandaag.", "Ik werk vandaag niet.", "Niet ik werk vandaag."],
    correctIndex: 1,
    explanationRu: "Отрицание всей ситуации в конкретный день: 'niet' ставится после обстоятельства времени 'vandaag'.",
  } as PracticeItem),
  base({
    id: "neg-pos-gen-3",
    taskType: "cloze",
    topic: "gezondheid",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    textWithBlank: "Ik heb dat medicijn ___ nodig. (niet)",
    answer: "niet",
    acceptableVariants: ["niet"],
    explanationRu: "'Niet' стоит перед прилагательным/предикативом 'nodig', который оно отрицает.",
  } as PracticeItem),
  base({
    id: "neg-pos-gen-4",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    prompt: "Kies de juiste zin.",
    options: ["Ik begrijp deze les niet.", "Ik begrijp niet deze les.", "Niet ik begrijp deze les."],
    correctIndex: 0,
    explanationRu: "'Niet' стоит после определённого прямого дополнения 'deze les', перед которым его ставить нельзя.",
  } as PracticeItem),
  base({
    id: "neg-pos-gen-5",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "negation_position",
    errorCodes: ["ERR_NEG_POS"],
    prompt: "Kies de juiste zin.",
    options: ["De verwarming werkt niet.", "De verwarming niet werkt.", "Niet de verwarming werkt."],
    correctIndex: 0,
    explanationRu: "При отсутствии дополнения 'niet' ставится сразу после глагола, в конце предложения.",
  } as PracticeItem),

  base({
    id: "plur-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    prompt: "Kies het juiste meervoud van 'tafel'.",
    options: ["tafels", "tafelen", "tafeles"],
    correctIndex: 0,
    explanationRu: "'Tafel' образует множественное число на -s: 'tafels'.",
  } as PracticeItem),
  base({
    id: "plur-gen-2",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    prompt: "Kies het juiste meervoud van 'dokter'.",
    options: ["dokters", "dokteren", "doktoren"],
    correctIndex: 0,
    explanationRu: "'Dokter' образует множественное число на -s: 'dokters'.",
  } as PracticeItem),
  base({
    id: "plur-gen-3",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    prompt: "Kies het juiste meervoud van 'baan'.",
    options: ["banen", "baans", "baanen"],
    correctIndex: 0,
    explanationRu: "'Baan' образует множественное число на -en с удлинением гласной: 'banen'.",
  } as PracticeItem),
  base({
    id: "plur-gen-4",
    taskType: "cloze",
    topic: "familie",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    textWithBlank: "Ik heb twee ___. (broer)",
    answer: "broers",
    acceptableVariants: ["broers"],
    explanationRu: "'Broer' образует множественное число на -s: 'broers'.",
  } as PracticeItem),

  base({
    id: "dim-art-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "diminutive_article",
    errorCodes: ["ERR_DIM_ART"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de huisje", "het huisje", "een huisje die"],
    correctIndex: 1,
    explanationRu: "Все уменьшительные существительные среднего рода — используем 'het': 'het huisje'.",
  } as PracticeItem),
  base({
    id: "dim-art-gen-2",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "diminutive_article",
    errorCodes: ["ERR_DIM_ART"],
    prompt: "Kies het juiste lidwoord.",
    options: ["de tabletje", "het tabletje", "een tabletje deze"],
    correctIndex: 1,
    explanationRu: "Даже если основа слова 'de'-рода, уменьшительная форма всегда 'het': 'het tabletje'.",
  } as PracticeItem),
  base({
    id: "dim-art-gen-3",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "diminutive_article",
    errorCodes: ["ERR_DIM_ART"],
    prompt: "Kies het juiste lidwoord.",
    options: ["het tafeltje", "de tafeltje", "een tafeltje die"],
    correctIndex: 0,
    explanationRu: "'Tafel' — de-слово, но уменьшительное 'tafeltje' всегда среднего рода: 'het tafeltje'.",
  } as PracticeItem),
  base({
    id: "dim-art-gen-4",
    taskType: "cloze",
    topic: "familie",
    grammarTarget: "diminutive_article",
    errorCodes: ["ERR_DIM_ART"],
    textWithBlank: "___ kopje staat op tafel. (het)",
    answer: "Het",
    acceptableVariants: ["Het"],
    explanationRu: "Уменьшительное 'kopje' всегда с артиклем 'het', независимо от рода основы 'kop'.",
  } as PracticeItem),

  base({
    id: "prep-fixed-gen-1",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies het juiste voorzetsel.",
    options: ["Ik wacht op de trein.", "Ik wacht voor de trein.", "Ik wacht aan de trein."],
    correctIndex: 0,
    explanationRu: "Фиксированное сочетание 'wachten op' (ждать что-то/кого-то) — не 'voor' и не 'aan'.",
  } as PracticeItem),
  base({
    id: "prep-fixed-gen-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies het juiste voorzetsel.",
    options: ["Ik denk aan mijn familie.", "Ik denk op mijn familie.", "Ik denk voor mijn familie."],
    correctIndex: 0,
    explanationRu: "Фиксированное сочетание 'denken aan' (думать о ком-то/чём-то).",
  } as PracticeItem),
  base({
    id: "prep-fixed-gen-3",
    taskType: "cloze",
    topic: "onderwijs",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    textWithBlank: "Ik ben geïnteresseerd ___ deze cursus. (in)",
    answer: "in",
    acceptableVariants: ["in"],
    explanationRu: "Фиксированное сочетание 'geïnteresseerd in' (заинтересован в чём-то).",
  } as PracticeItem),
  base({
    id: "prep-fixed-gen-4",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies het juiste voorzetsel.",
    options: ["Ik ben blij met het resultaat.", "Ik ben blij voor het resultaat.", "Ik ben blij op het resultaat."],
    correctIndex: 0,
    explanationRu: "Фиксированное сочетание 'blij met' (рад чему-то).",
  } as PracticeItem),
  base({
    id: "prep-fixed-gen-5",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "fixed_preposition",
    errorCodes: ["ERR_PREP_FIXED"],
    prompt: "Kies het juiste voorzetsel.",
    options: ["Ik solliciteer naar een baan.", "Ik solliciteer op een baan.", "Ik solliciteer voor een baan."],
    correctIndex: 1,
    explanationRu: "Фиксированное сочетание 'solliciteren op' (претендовать на должность).",
  } as PracticeItem),

  base({
    id: "colloc-gen-1",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    prompt: "Kies de juiste combinatie.",
    options: ["een afspraak maken", "een afspraak doen", "een afspraak nemen"],
    correctIndex: 0,
    explanationRu: "Стандартная коллокация — 'een afspraak maken' (назначить встречу), не 'doen' или 'nemen'.",
  } as PracticeItem),
  base({
    id: "colloc-gen-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    prompt: "Kies de juiste combinatie.",
    options: ["een beslissing nemen", "een beslissing maken", "een beslissing doen"],
    correctIndex: 0,
    explanationRu: "Стандартная коллокация — 'een beslissing nemen' (принять решение).",
  } as PracticeItem),
  base({
    id: "colloc-gen-3",
    taskType: "cloze",
    topic: "onderwijs",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    textWithBlank: "Ik wil graag een cursus ___. (volgen)",
    answer: "volgen",
    acceptableVariants: ["volgen"],
    explanationRu: "Стандартная коллокация — 'een cursus volgen' (проходить курс).",
  } as PracticeItem),
  base({
    id: "colloc-gen-4",
    taskType: "mc",
    topic: "geld",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    prompt: "Kies de juiste combinatie.",
    options: ["een rekening betalen", "een rekening maken", "een rekening geven"],
    correctIndex: 0,
    explanationRu: "Стандартная коллокация — 'een rekening betalen' (оплатить счёт).",
  } as PracticeItem),
  base({
    id: "colloc-gen-5",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "collocation",
    errorCodes: ["ERR_COLLOC"],
    prompt: "Kies de juiste combinatie.",
    options: ["aandacht besteden aan", "aandacht maken aan", "aandacht doen aan"],
    correctIndex: 0,
    explanationRu: "Стандартная коллокация — 'aandacht besteden aan' (уделять внимание чему-то).",
  } as PracticeItem),

  base({
    id: "vlength-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "vowel_length",
    errorCodes: ["ERR_PHON_VLENGTH"],
    prompt: "Welk woord heeft een lange klinker?",
    options: ["kat", "kaas", "kast"],
    correctIndex: 1,
    explanationRu: "'Kaas' с двойной 'aa' — долгий гласный, в отличие от 'kat' и 'kast' с кратким 'a'.",
  } as PracticeItem),
  base({
    id: "vlength-gen-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "vowel_length",
    errorCodes: ["ERR_PHON_VLENGTH"],
    prompt: "Welk woord heeft een korte klinker?",
    options: ["huren", "hun", "huur"],
    correctIndex: 1,
    explanationRu: "'Hun' с одиночной гласной в закрытом слоге — краткий звук, в отличие от 'huren'/'huur'.",
  } as PracticeItem),
  base({
    id: "vlength-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "vowel_length",
    errorCodes: ["ERR_PHON_VLENGTH"],
    prompt: "Welk woord heeft een lange klinker?",
    options: ["pen", "peen", "pet"],
    correctIndex: 1,
    explanationRu: "'Peen' с двойной 'ee' — долгий гласный, в отличие от кратких 'pen'/'pet'.",
  } as PracticeItem),
  base({
    id: "vlength-gen-4",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "vowel_length",
    errorCodes: ["ERR_PHON_VLENGTH"],
    prompt: "Welk woord heeft een korte klinker?",
    options: ["bonen", "bon", "boon"],
    correctIndex: 1,
    explanationRu: "'Bon' с одиночной гласной в закрытом слоге — краткий звук.",
  } as PracticeItem),

  base({
    id: "frontround-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "front_rounded_vowels",
    errorCodes: ["ERR_PHON_FRONTROUND"],
    prompt: "Welk woord bevat de klank /y/ (zoals in 'muur')?",
    options: ["huur", "hoor", "haar"],
    correctIndex: 0,
    explanationRu: "'Huur' содержит округлённый передний гласный /y/ — губы округлены, язык впереди, как во французском 'u'.",
  } as PracticeItem),
  base({
    id: "frontround-gen-2",
    taskType: "mc",
    topic: "dagelijks_leven",
    grammarTarget: "front_rounded_vowels",
    errorCodes: ["ERR_PHON_FRONTROUND"],
    prompt: "Welk woord bevat de klank /ø/ (zoals in 'deur')?",
    options: ["deur", "door", "daar"],
    correctIndex: 0,
    explanationRu: "'Deur' содержит округлённый передний гласный /ø/ — похож на немецкое 'ö'.",
  } as PracticeItem),
  base({
    id: "frontround-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "front_rounded_vowels",
    errorCodes: ["ERR_PHON_FRONTROUND"],
    prompt: "Welk woord bevat de klank /y/ (zoals in 'muur')?",
    options: ["duur", "door", "daar"],
    correctIndex: 0,
    explanationRu: "'Duur' содержит округлённый передний гласный /y/, отсутствующий в русском языке.",
  } as PracticeItem),
  base({
    id: "frontround-gen-4",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "front_rounded_vowels",
    errorCodes: ["ERR_PHON_FRONTROUND"],
    prompt: "Welk woord bevat de klank /ø/ (zoals in 'deur')?",
    options: ["kleur", "klaar", "kloor"],
    correctIndex: 0,
    explanationRu: "'Kleur' содержит округлённый передний гласный /ø/ — типичная трудность для русскоговорящих.",
  } as PracticeItem),

  base({
    id: "devoice-gen-1",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "final_devoicing",
    errorCodes: ["ERR_PHON_DEVOICE"],
    prompt: "Hoe klinkt de laatste medeklinker van 'huis'?",
    options: ["stemhebbend [z]", "stemloos [s]", "helemaal niet uitgesproken"],
    correctIndex: 1,
    explanationRu: "В конце слова звонкие согласные оглушаются: 'huis' произносится с глухим [s], хотя во множественном числе 'huizen' звучит [z].",
  } as PracticeItem),
  base({
    id: "devoice-gen-2",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "final_devoicing",
    errorCodes: ["ERR_PHON_DEVOICE"],
    prompt: "Hoe klinkt de laatste medeklinker van 'baan'?",
    options: ["stemhebbend [d]", "stemloos [t]", "stemhebbend [b]"],
    correctIndex: 1,
    explanationRu: "Финальное оглушение: если бы 'baan' оканчивалось на 'd' (как в 'goed'), оно бы звучало как глухое [t].",
  } as PracticeItem),
  base({
    id: "devoice-gen-3",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "final_devoicing",
    errorCodes: ["ERR_PHON_DEVOICE"],
    prompt: "Hoe klinkt de laatste medeklinker van 'goed'?",
    options: ["stemhebbend [d]", "stemloos [t]", "stil, niet uitgesproken"],
    correctIndex: 1,
    explanationRu: "'Goed' оканчивается на глухой [t], хотя пишется 'd' — сравните форму 'goede' со звонким [d].",
  } as PracticeItem),
  base({
    id: "devoice-gen-4",
    taskType: "mc",
    topic: "geld",
    grammarTarget: "final_devoicing",
    errorCodes: ["ERR_PHON_DEVOICE"],
    prompt: "Hoe klinkt de laatste medeklinker van 'prijs'?",
    options: ["stemhebbend [z]", "stemloos [s]", "stemhebbend [zj]"],
    correctIndex: 1,
    explanationRu: "'Prijs' оканчивается на глухой [s], сравните со звонким [z] в форме множественного числа 'prijzen'.",
  } as PracticeItem),

  base({
    id: "xg-gen-1",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "x_g_contrast",
    errorCodes: ["ERR_PHON_XG"],
    prompt: "Welk woord begint met de Nederlandse 'g' (niet Russisch [х] of [г])?",
    options: ["gemeente", "kamer", "tafel"],
    correctIndex: 0,
    explanationRu: "Нидерландское 'g' — гортанный щелевой звук, глубже русского [х] и не такой, как [г].",
  } as PracticeItem),
  base({
    id: "xg-gen-2",
    taskType: "mc",
    topic: "wonen",
    grammarTarget: "x_g_contrast",
    errorCodes: ["ERR_PHON_XG"],
    prompt: "Welk woord bevat de Nederlandse 'ch' (niet Russisch [х])?",
    options: ["nacht", "tafel", "deur"],
    correctIndex: 0,
    explanationRu: "'Ch' в 'nacht' произносится глубже в горле, чем русское [х] — как гортанный щелевой звук.",
  } as PracticeItem),
  base({
    id: "xg-gen-3",
    taskType: "mc",
    topic: "werk",
    grammarTarget: "x_g_contrast",
    errorCodes: ["ERR_PHON_XG"],
    prompt: "Welk woord begint met de Nederlandse 'g' (niet Russisch [х] of [г])?",
    options: ["gesprek", "salaris", "kantoor"],
    correctIndex: 0,
    explanationRu: "Нидерландское 'g' в 'gesprek' — не русское [г] и не [х], а глубокий гортанный щелевой звук.",
  } as PracticeItem),
  base({
    id: "xg-gen-4",
    taskType: "mc",
    topic: "gezondheid",
    grammarTarget: "x_g_contrast",
    errorCodes: ["ERR_PHON_XG"],
    prompt: "Welk woord bevat de Nederlandse 'ch'?",
    options: ["recht", "recept", "tandarts"],
    correctIndex: 0,
    explanationRu: "'Ch' в 'recht' — глубокий гортанный щелевой звук, а не русское [х].",
  } as PracticeItem),
  base({
    id: "plur-gen-5",
    taskType: "mc",
    topic: "onderwijs",
    grammarTarget: "plural_selection",
    errorCodes: ["ERR_PLUR"],
    prompt: "Kies het juiste meervoud van 'les'.",
    options: ["lessen", "lesen", "lessies"],
    correctIndex: 0,
    explanationRu: "'Les' образует множественное число с удвоением 's' перед -en: 'lessen'.",
  } as PracticeItem),
];
