import { NounBundle } from "../types";

// §4 — sample of the SUBTLEX-NL × NT2Lex intersected core, stored as full
// noun bundles (never bare translation pairs). This is a seed slice, not
// the full ~2,000-5,000 lemma target from §4 — real authoring intersects
// SUBTLEX-NL frequency with NT2Lex CEFR grading and exam-domain vocabulary.
export const NOUN_BUNDLES: NounBundle[] = [
  {
    lemma: "huis",
    article: "het",
    plural: "huizen",
    diminutive: "huisje",
    diminutivePlural: "huisjes",
    adjAgreement: { definite: "het grote huis", indefinite: "een groot huis" },
    collocations: ["een huis kopen", "thuis zijn", "het huis uit gaan"],
    cefrLevel: "A2",
  },
  {
    lemma: "afspraak",
    article: "de",
    plural: "afspraken",
    diminutive: "afspraakje",
    diminutivePlural: "afspraakjes",
    adjAgreement: { definite: "de belangrijke afspraak", indefinite: "een belangrijke afspraak" },
    collocations: ["een afspraak maken", "een afspraak afzeggen", "op tijd komen voor een afspraak"],
    cefrLevel: "A2",
  },
  {
    lemma: "gemeente",
    article: "de",
    plural: "gemeenten",
    diminutive: "gemeentetje",
    diminutivePlural: "gemeentetjes",
    adjAgreement: { definite: "de lokale gemeente", indefinite: "een lokale gemeente" },
    collocations: ["je inschrijven bij de gemeente", "naar de gemeente gaan"],
    cefrLevel: "A2",
  },
  {
    lemma: "huisarts",
    article: "de",
    plural: "huisartsen",
    diminutive: "huisartsje",
    diminutivePlural: "huisartsjes",
    adjAgreement: { definite: "de nieuwe huisarts", indefinite: "een nieuwe huisarts" },
    collocations: ["een afspraak bij de huisarts", "je inschrijven bij een huisarts"],
    cefrLevel: "A2",
  },
  {
    lemma: "opleiding",
    article: "de",
    plural: "opleidingen",
    diminutive: "opleidinkje",
    diminutivePlural: "opleidinkjes",
    adjAgreement: { definite: "de moeilijke opleiding", indefinite: "een moeilijke opleiding" },
    collocations: ["een opleiding volgen", "een opleiding afmaken"],
    cefrLevel: "B1",
  },
  {
    lemma: "sollicitatie",
    article: "de",
    plural: "sollicitaties",
    diminutive: "sollicitatietje",
    diminutivePlural: "sollicitatietjes",
    adjAgreement: { definite: "de succesvolle sollicitatie", indefinite: "een succesvolle sollicitatie" },
    collocations: ["solliciteren naar een baan", "een sollicitatiebrief schrijven"],
    cefrLevel: "B1",
  },
  {
    lemma: "verzekering",
    article: "de",
    plural: "verzekeringen",
    diminutive: "verzekeringetje",
    diminutivePlural: "verzekeringetjes",
    adjAgreement: { definite: "de verplichte verzekering", indefinite: "een verplichte verzekering" },
    collocations: ["een verzekering afsluiten", "zorgverzekering betalen"],
    cefrLevel: "B1",
  },
  {
    lemma: "kind",
    article: "het",
    plural: "kinderen",
    diminutive: "kindje",
    diminutivePlural: "kindjes",
    adjAgreement: { definite: "het kleine kind", indefinite: "een klein kind" },
    collocations: ["kinderen opvoeden", "een kind krijgen"],
    cefrLevel: "A2",
  },
  {
    lemma: "baan",
    article: "de",
    plural: "banen",
    diminutive: "baantje",
    diminutivePlural: "baantjes",
    adjAgreement: { definite: "de goede baan", indefinite: "een goede baan" },
    collocations: ["een baan zoeken", "een baan vinden", "fulltime werken"],
    cefrLevel: "A2",
  },
  {
    lemma: "contract",
    article: "het",
    plural: "contracten",
    diminutive: "contractje",
    diminutivePlural: "contractjes",
    adjAgreement: { definite: "het nieuwe contract", indefinite: "een nieuw contract" },
    collocations: ["een contract tekenen", "een tijdelijk contract"],
    cefrLevel: "B1",
  },
  {
    lemma: "salaris",
    article: "het",
    plural: "salarissen",
    diminutive: "salarisje",
    diminutivePlural: "salarisjes",
    adjAgreement: { definite: "het hoge salaris", indefinite: "een hoog salaris" },
    collocations: ["salaris krijgen", "een goed salaris verdienen"],
    cefrLevel: "B1",
  },
  {
    lemma: "woning",
    article: "de",
    plural: "woningen",
    diminutive: "woninkje",
    diminutivePlural: "woninkjes",
    adjAgreement: { definite: "de kleine woning", indefinite: "een kleine woning" },
    collocations: ["een woning huren", "op zoek naar een woning"],
    cefrLevel: "A2",
  },
  {
    lemma: "buurt",
    article: "de",
    plural: "buurten",
    diminutive: "buurtje",
    diminutivePlural: "buurtjes",
    adjAgreement: { definite: "de rustige buurt", indefinite: "een rustige buurt" },
    collocations: ["in de buurt wonen", "een rustige buurt zoeken"],
    cefrLevel: "A2",
  },
  {
    lemma: "ziekenhuis",
    article: "het",
    plural: "ziekenhuizen",
    diminutive: "ziekenhuisje",
    diminutivePlural: "ziekenhuisjes",
    adjAgreement: { definite: "het grote ziekenhuis", indefinite: "een groot ziekenhuis" },
    collocations: ["naar het ziekenhuis gaan", "in het ziekenhuis liggen"],
    cefrLevel: "A2",
  },
  {
    lemma: "medicijn",
    article: "het",
    plural: "medicijnen",
    diminutive: "medicijntje",
    diminutivePlural: "medicijntjes",
    adjAgreement: { definite: "het sterke medicijn", indefinite: "een sterk medicijn" },
    collocations: ["medicijnen innemen", "medicijnen halen bij de apotheek"],
    cefrLevel: "A2",
  },
  {
    lemma: "school",
    article: "de",
    plural: "scholen",
    diminutive: "schooltje",
    diminutivePlural: "schooltjes",
    adjAgreement: { definite: "de goede school", indefinite: "een goede school" },
    collocations: ["naar school gaan", "een kind naar school brengen"],
    cefrLevel: "A2",
  },
  {
    lemma: "cursus",
    article: "de",
    plural: "cursussen",
    diminutive: "cursusje",
    diminutivePlural: "cursusjes",
    adjAgreement: { definite: "de nieuwe cursus", indefinite: "een nieuwe cursus" },
    collocations: ["een cursus volgen", "Nederlands leren via een cursus"],
    cefrLevel: "A2",
  },
  {
    lemma: "brief",
    article: "de",
    plural: "brieven",
    diminutive: "briefje",
    diminutivePlural: "briefjes",
    adjAgreement: { definite: "de belangrijke brief", indefinite: "een belangrijke brief" },
    collocations: ["een brief schrijven", "een brief ontvangen"],
    cefrLevel: "A2",
  },
  {
    lemma: "formulier",
    article: "het",
    plural: "formulieren",
    diminutive: "formuliertje",
    diminutivePlural: "formuliertjes",
    adjAgreement: { definite: "het lange formulier", indefinite: "een lang formulier" },
    collocations: ["een formulier invullen", "een formulier opsturen"],
    cefrLevel: "B1",
  },
  {
    lemma: "paspoort",
    article: "het",
    plural: "paspoorten",
    diminutive: "paspoortje",
    diminutivePlural: "paspoortjes",
    adjAgreement: { definite: "het geldige paspoort", indefinite: "een geldig paspoort" },
    collocations: ["een paspoort aanvragen", "je paspoort meenemen"],
    cefrLevel: "A2",
  },
  {
    lemma: "sleutel",
    article: "de",
    plural: "sleutels",
    diminutive: "sleuteltje",
    diminutivePlural: "sleuteltjes",
    adjAgreement: { definite: "de nieuwe sleutel", indefinite: "een nieuwe sleutel" },
    collocations: ["de sleutel van het huis", "een sleutel vergeten"],
    cefrLevel: "A2",
  },
  {
    lemma: "dokter",
    article: "de",
    plural: "dokters",
    diminutive: "doktertje",
    diminutivePlural: "doktertjes",
    adjAgreement: { definite: "de goede dokter", indefinite: "een goede dokter" },
    collocations: ["naar de dokter gaan", "een afspraak bij de dokter"],
    cefrLevel: "A2",
  },
  {
    lemma: "tandarts",
    article: "de",
    plural: "tandartsen",
    diminutive: "tandartsje",
    diminutivePlural: "tandartsjes",
    adjAgreement: { definite: "de nieuwe tandarts", indefinite: "een nieuwe tandarts" },
    collocations: ["naar de tandarts gaan", "een afspraak bij de tandarts"],
    cefrLevel: "A2",
  },
  {
    lemma: "recept",
    article: "het",
    plural: "recepten",
    diminutive: "receptje",
    diminutivePlural: "receptjes",
    adjAgreement: { definite: "het nieuwe recept", indefinite: "een nieuw recept" },
    collocations: ["een recept krijgen", "een recept inleveren bij de apotheek"],
    cefrLevel: "A2",
  },
  {
    lemma: "pas",
    article: "de",
    plural: "passen",
    diminutive: "pasje",
    diminutivePlural: "pasjes",
    adjAgreement: { definite: "de geldige pas", indefinite: "een geldige pas" },
    collocations: ["een pas aanvragen", "je pas laten zien"],
    cefrLevel: "A2",
  },
  {
    lemma: "inkomen",
    article: "het",
    plural: "inkomens",
    diminutive: "inkomentje",
    diminutivePlural: "inkomentjes",
    adjAgreement: { definite: "het vaste inkomen", indefinite: "een vast inkomen" },
    collocations: ["een vast inkomen hebben", "inkomen opgeven"],
    cefrLevel: "B1",
  },
  {
    lemma: "adres",
    article: "het",
    plural: "adressen",
    diminutive: "adresje",
    diminutivePlural: "adresjes",
    adjAgreement: { definite: "het nieuwe adres", indefinite: "een nieuw adres" },
    collocations: ["je adres doorgeven", "een nieuw adres hebben"],
    cefrLevel: "A2",
  },
  {
    lemma: "les",
    article: "de",
    plural: "lessen",
    diminutive: "lesje",
    diminutivePlural: "lesjes",
    adjAgreement: { definite: "de moeilijke les", indefinite: "een moeilijke les" },
    collocations: ["een les volgen", "Nederlandse les krijgen"],
    cefrLevel: "A2",
  },
  {
    lemma: "rekening",
    article: "de",
    plural: "rekeningen",
    diminutive: "rekeningetje",
    diminutivePlural: "rekeningetjes",
    adjAgreement: { definite: "de hoge rekening", indefinite: "een hoge rekening" },
    collocations: ["een rekening betalen", "een hoge rekening krijgen"],
    cefrLevel: "A2",
  },
  {
    lemma: "polis",
    article: "de",
    plural: "polissen",
    diminutive: "polisje",
    diminutivePlural: "polisjes",
    adjAgreement: { definite: "de dure polis", indefinite: "een dure polis" },
    collocations: ["een polis afsluiten", "de polis controleren"],
    cefrLevel: "B1",
  },

  // --- +100 batch: wonen, familie, eten/winkelen, kleding, lichaam, tijd/weer,
  // vervoer, werk/overheid, gezondheid. Same schema and grammar conventions
  // as the seed slice above.
  {
    lemma: "tafel",
    article: "de",
    plural: "tafels",
    diminutive: "tafeltje",
    diminutivePlural: "tafeltjes",
    adjAgreement: { definite: "de grote tafel", indefinite: "een grote tafel" },
    collocations: ["de tafel dekken", "aan tafel zitten"],
    cefrLevel: "A2",
  },
  {
    lemma: "stoel",
    article: "de",
    plural: "stoelen",
    diminutive: "stoeltje",
    diminutivePlural: "stoeltjes",
    adjAgreement: { definite: "de harde stoel", indefinite: "een harde stoel" },
    collocations: ["op een stoel zitten", "een stoel bijschuiven"],
    cefrLevel: "A2",
  },
  {
    lemma: "bed",
    article: "het",
    plural: "bedden",
    diminutive: "bedje",
    diminutivePlural: "bedjes",
    adjAgreement: { definite: "het brede bed", indefinite: "een breed bed" },
    collocations: ["naar bed gaan", "het bed opmaken"],
    cefrLevel: "A2",
  },
  {
    lemma: "kast",
    article: "de",
    plural: "kasten",
    diminutive: "kastje",
    diminutivePlural: "kastjes",
    adjAgreement: { definite: "de volle kast", indefinite: "een volle kast" },
    collocations: ["kleren in de kast hangen", "een kast opruimen"],
    cefrLevel: "A2",
  },
  {
    lemma: "lamp",
    article: "de",
    plural: "lampen",
    diminutive: "lampje",
    diminutivePlural: "lampjes",
    adjAgreement: { definite: "de felle lamp", indefinite: "een felle lamp" },
    collocations: ["de lamp aandoen", "een lamp vervangen"],
    cefrLevel: "A2",
  },
  {
    lemma: "deken",
    article: "de",
    plural: "dekens",
    diminutive: "dekentje",
    diminutivePlural: "dekentjes",
    adjAgreement: { definite: "de warme deken", indefinite: "een warme deken" },
    collocations: ["onder de deken kruipen", "een extra deken pakken"],
    cefrLevel: "A2",
  },
  {
    lemma: "kussen",
    article: "het",
    plural: "kussens",
    diminutive: "kussentje",
    diminutivePlural: "kussentjes",
    adjAgreement: { definite: "het zachte kussen", indefinite: "een zacht kussen" },
    collocations: ["je hoofd op het kussen leggen", "een kussen opschudden"],
    cefrLevel: "A2",
  },
  {
    lemma: "spiegel",
    article: "de",
    plural: "spiegels",
    diminutive: "spiegeltje",
    diminutivePlural: "spiegeltjes",
    adjAgreement: { definite: "de grote spiegel", indefinite: "een grote spiegel" },
    collocations: ["in de spiegel kijken", "een spiegel ophangen"],
    cefrLevel: "A2",
  },
  {
    lemma: "douche",
    article: "de",
    plural: "douches",
    diminutive: "douchetje",
    diminutivePlural: "douchetjes",
    adjAgreement: { definite: "de warme douche", indefinite: "een warme douche" },
    collocations: ["onder de douche gaan", "de douche schoonmaken"],
    cefrLevel: "A2",
  },
  {
    lemma: "wasmachine",
    article: "de",
    plural: "wasmachines",
    diminutive: "wasmachinetje",
    diminutivePlural: "wasmachinetjes",
    adjAgreement: { definite: "de nieuwe wasmachine", indefinite: "een nieuwe wasmachine" },
    collocations: ["de wasmachine aanzetten", "de wasmachine repareren"],
    cefrLevel: "B1",
  },
  {
    lemma: "koelkast",
    article: "de",
    plural: "koelkasten",
    diminutive: "koelkastje",
    diminutivePlural: "koelkastjes",
    adjAgreement: { definite: "de volle koelkast", indefinite: "een volle koelkast" },
    collocations: ["eten in de koelkast zetten", "de koelkast leegmaken"],
    cefrLevel: "A2",
  },
  {
    lemma: "balkon",
    article: "het",
    plural: "balkons",
    diminutive: "balkonnetje",
    diminutivePlural: "balkonnetjes",
    adjAgreement: { definite: "het kleine balkon", indefinite: "een klein balkon" },
    collocations: ["op het balkon zitten", "planten op het balkon zetten"],
    cefrLevel: "B1",
  },
  {
    lemma: "tuin",
    article: "de",
    plural: "tuinen",
    diminutive: "tuintje",
    diminutivePlural: "tuintjes",
    adjAgreement: { definite: "de groene tuin", indefinite: "een groene tuin" },
    collocations: ["in de tuin werken", "de tuin onderhouden"],
    cefrLevel: "A2",
  },
  {
    lemma: "trap",
    article: "de",
    plural: "trappen",
    diminutive: "trapje",
    diminutivePlural: "trapjes",
    adjAgreement: { definite: "de steile trap", indefinite: "een steile trap" },
    collocations: ["de trap op lopen", "van de trap vallen"],
    cefrLevel: "A2",
  },
  {
    lemma: "muur",
    article: "de",
    plural: "muren",
    diminutive: "muurtje",
    diminutivePlural: "muurtjes",
    adjAgreement: { definite: "de witte muur", indefinite: "een witte muur" },
    collocations: ["een muur verven", "tegen de muur leunen"],
    cefrLevel: "A2",
  },
  {
    lemma: "dak",
    article: "het",
    plural: "daken",
    diminutive: "dakje",
    diminutivePlural: "dakjes",
    adjAgreement: { definite: "het hoge dak", indefinite: "een hoog dak" },
    collocations: ["een dak boven je hoofd hebben", "het dak repareren"],
    cefrLevel: "A2",
  },
  {
    lemma: "vloer",
    article: "de",
    plural: "vloeren",
    diminutive: "vloertje",
    diminutivePlural: "vloertjes",
    adjAgreement: { definite: "de schone vloer", indefinite: "een schone vloer" },
    collocations: ["de vloer dweilen", "op de vloer zitten"],
    cefrLevel: "A2",
  },
  {
    lemma: "plafond",
    article: "het",
    plural: "plafonds",
    diminutive: "plafondje",
    diminutivePlural: "plafondjes",
    adjAgreement: { definite: "het hoge plafond", indefinite: "een hoog plafond" },
    collocations: ["naar het plafond kijken", "het plafond schilderen"],
    cefrLevel: "B1",
  },
  {
    lemma: "gordijn",
    article: "het",
    plural: "gordijnen",
    diminutive: "gordijntje",
    diminutivePlural: "gordijntjes",
    adjAgreement: { definite: "het lange gordijn", indefinite: "een lang gordijn" },
    collocations: ["de gordijnen dichtdoen", "nieuwe gordijnen ophangen"],
    cefrLevel: "B1",
  },
  {
    lemma: "brievenbus",
    article: "de",
    plural: "brievenbussen",
    diminutive: "brievenbusje",
    diminutivePlural: "brievenbusjes",
    adjAgreement: { definite: "de volle brievenbus", indefinite: "een volle brievenbus" },
    collocations: ["post in de brievenbus doen", "de brievenbus legen"],
    cefrLevel: "A2",
  },
  {
    lemma: "broer",
    article: "de",
    plural: "broers",
    diminutive: "broertje",
    diminutivePlural: "broertjes",
    adjAgreement: { definite: "de oudere broer", indefinite: "een oudere broer" },
    collocations: ["mijn broer bellen", "met je broer opgroeien"],
    cefrLevel: "A2",
  },
  {
    lemma: "zus",
    article: "de",
    plural: "zussen",
    diminutive: "zusje",
    diminutivePlural: "zusjes",
    adjAgreement: { definite: "de jongere zus", indefinite: "een jongere zus" },
    collocations: ["mijn zus opzoeken", "een zus hebben"],
    cefrLevel: "A2",
  },
  {
    lemma: "ouder",
    article: "de",
    plural: "ouders",
    diminutive: "oudertje",
    diminutivePlural: "oudertjes",
    adjAgreement: { definite: "de zorgzame ouder", indefinite: "een zorgzame ouder" },
    collocations: ["bij je ouders wonen", "een gesprek met de ouders"],
    cefrLevel: "A2",
  },
  {
    lemma: "dochter",
    article: "de",
    plural: "dochters",
    diminutive: "dochtertje",
    diminutivePlural: "dochtertjes",
    adjAgreement: { definite: "de kleine dochter", indefinite: "een kleine dochter" },
    collocations: ["je dochter naar school brengen", "trots zijn op je dochter"],
    cefrLevel: "A2",
  },
  {
    lemma: "zoon",
    article: "de",
    plural: "zonen",
    diminutive: "zoontje",
    diminutivePlural: "zoontjes",
    adjAgreement: { definite: "de oudste zoon", indefinite: "een oudste zoon" },
    collocations: ["je zoon ophalen", "met je zoon spelen"],
    cefrLevel: "A2",
  },
  {
    lemma: "oma",
    article: "de",
    plural: "oma's",
    diminutive: "omaatje",
    diminutivePlural: "omaatjes",
    adjAgreement: { definite: "de lieve oma", indefinite: "een lieve oma" },
    collocations: ["op bezoek bij oma", "oma helpen"],
    cefrLevel: "A2",
  },
  {
    lemma: "opa",
    article: "de",
    plural: "opa's",
    diminutive: "opaatje",
    diminutivePlural: "opaatjes",
    adjAgreement: { definite: "de trotse opa", indefinite: "een trotse opa" },
    collocations: ["met opa wandelen", "opa bellen"],
    cefrLevel: "A2",
  },
  {
    lemma: "neef",
    article: "de",
    plural: "neven",
    diminutive: "neefje",
    diminutivePlural: "neefjes",
    adjAgreement: { definite: "de jonge neef", indefinite: "een jonge neef" },
    collocations: ["mijn neef uitnodigen", "een neef in Nederland hebben"],
    cefrLevel: "B1",
  },
  {
    lemma: "nicht",
    article: "de",
    plural: "nichten",
    diminutive: "nichtje",
    diminutivePlural: "nichtjes",
    adjAgreement: { definite: "de lieve nicht", indefinite: "een lieve nicht" },
    collocations: ["mijn nicht bezoeken", "met je nicht praten"],
    cefrLevel: "B1",
  },
  {
    lemma: "buurvrouw",
    article: "de",
    plural: "buurvrouwen",
    diminutive: "buurvrouwtje",
    diminutivePlural: "buurvrouwtjes",
    adjAgreement: { definite: "de vriendelijke buurvrouw", indefinite: "een vriendelijke buurvrouw" },
    collocations: ["de buurvrouw groeten", "hulp vragen aan de buurvrouw"],
    cefrLevel: "A2",
  },
  {
    lemma: "brood",
    article: "het",
    plural: "broden",
    diminutive: "broodje",
    diminutivePlural: "broodjes",
    adjAgreement: { definite: "het verse brood", indefinite: "een vers brood" },
    collocations: ["brood kopen", "brood smeren"],
    cefrLevel: "A2",
  },
  {
    lemma: "kaas",
    article: "de",
    plural: "kazen",
    diminutive: "kaasje",
    diminutivePlural: "kaasjes",
    adjAgreement: { definite: "de jonge kaas", indefinite: "een jonge kaas" },
    collocations: ["kaas snijden", "een boterham met kaas"],
    cefrLevel: "A2",
  },
  {
    lemma: "appel",
    article: "de",
    plural: "appels",
    diminutive: "appeltje",
    diminutivePlural: "appeltjes",
    adjAgreement: { definite: "de zoete appel", indefinite: "een zoete appel" },
    collocations: ["een appel eten", "appels kopen op de markt"],
    cefrLevel: "A2",
  },
  {
    lemma: "groente",
    article: "de",
    plural: "groenten",
    diminutive: "groentetje",
    diminutivePlural: "groentetjes",
    adjAgreement: { definite: "de verse groente", indefinite: "een verse groente" },
    collocations: ["groente eten", "groente snijden"],
    cefrLevel: "A2",
  },
  {
    lemma: "winkel",
    article: "de",
    plural: "winkels",
    diminutive: "winkeltje",
    diminutivePlural: "winkeltjes",
    adjAgreement: { definite: "de drukke winkel", indefinite: "een drukke winkel" },
    collocations: ["naar de winkel gaan", "de winkel sluiten"],
    cefrLevel: "A2",
  },
  {
    lemma: "markt",
    article: "de",
    plural: "markten",
    diminutive: "marktje",
    diminutivePlural: "marktjes",
    adjAgreement: { definite: "de gezellige markt", indefinite: "een gezellige markt" },
    collocations: ["naar de markt gaan", "groente kopen op de markt"],
    cefrLevel: "A2",
  },
  {
    lemma: "boodschappentas",
    article: "de",
    plural: "boodschappentassen",
    diminutive: "boodschappentasje",
    diminutivePlural: "boodschappentasjes",
    adjAgreement: { definite: "de zware boodschappentas", indefinite: "een zware boodschappentas" },
    collocations: ["de boodschappentas dragen", "een boodschappentas vullen"],
    cefrLevel: "A2",
  },
  {
    lemma: "prijs",
    article: "de",
    plural: "prijzen",
    diminutive: "prijsje",
    diminutivePlural: "prijsjes",
    adjAgreement: { definite: "de hoge prijs", indefinite: "een hoge prijs" },
    collocations: ["de prijs controleren", "een goede prijs betalen"],
    cefrLevel: "A2",
  },
  {
    lemma: "korting",
    article: "de",
    plural: "kortingen",
    diminutive: "kortinkje",
    diminutivePlural: "kortinkjes",
    adjAgreement: { definite: "de mooie korting", indefinite: "een mooie korting" },
    collocations: ["korting krijgen", "een product met korting kopen"],
    cefrLevel: "B1",
  },
  {
    lemma: "bon",
    article: "de",
    plural: "bonnen",
    diminutive: "bonnetje",
    diminutivePlural: "bonnetjes",
    adjAgreement: { definite: "de lange bon", indefinite: "een lange bon" },
    collocations: ["het bonnetje bewaren", "een bon inleveren"],
    cefrLevel: "A2",
  },
  {
    lemma: "jas",
    article: "de",
    plural: "jassen",
    diminutive: "jasje",
    diminutivePlural: "jasjes",
    adjAgreement: { definite: "de warme jas", indefinite: "een warme jas" },
    collocations: ["je jas aantrekken", "een jas ophangen"],
    cefrLevel: "A2",
  },
  {
    lemma: "broek",
    article: "de",
    plural: "broeken",
    diminutive: "broekje",
    diminutivePlural: "broekjes",
    adjAgreement: { definite: "de nieuwe broek", indefinite: "een nieuwe broek" },
    collocations: ["een broek passen", "een broek wassen"],
    cefrLevel: "A2",
  },
  {
    lemma: "schoen",
    article: "de",
    plural: "schoenen",
    diminutive: "schoentje",
    diminutivePlural: "schoentjes",
    adjAgreement: { definite: "de nette schoen", indefinite: "een nette schoen" },
    collocations: ["je schoenen aandoen", "nieuwe schoenen kopen"],
    cefrLevel: "A2",
  },
  {
    lemma: "trui",
    article: "de",
    plural: "truien",
    diminutive: "truitje",
    diminutivePlural: "truitjes",
    adjAgreement: { definite: "de dikke trui", indefinite: "een dikke trui" },
    collocations: ["een trui aantrekken", "een trui breien"],
    cefrLevel: "A2",
  },
  {
    lemma: "muts",
    article: "de",
    plural: "mutsen",
    diminutive: "mutsje",
    diminutivePlural: "mutsjes",
    adjAgreement: { definite: "de warme muts", indefinite: "een warme muts" },
    collocations: ["een muts opzetten", "een muts dragen in de winter"],
    cefrLevel: "A2",
  },
  {
    lemma: "sjaal",
    article: "de",
    plural: "sjaals",
    diminutive: "sjaaltje",
    diminutivePlural: "sjaaltjes",
    adjAgreement: { definite: "de lange sjaal", indefinite: "een lange sjaal" },
    collocations: ["een sjaal omdoen", "een sjaal kopen"],
    cefrLevel: "A2",
  },
  {
    lemma: "handschoen",
    article: "de",
    plural: "handschoenen",
    diminutive: "handschoentje",
    diminutivePlural: "handschoentjes",
    adjAgreement: { definite: "de warme handschoen", indefinite: "een warme handschoen" },
    collocations: ["handschoenen aantrekken", "een handschoen kwijtraken"],
    cefrLevel: "A2",
  },
  {
    lemma: "hoed",
    article: "de",
    plural: "hoeden",
    diminutive: "hoedje",
    diminutivePlural: "hoedjes",
    adjAgreement: { definite: "de mooie hoed", indefinite: "een mooie hoed" },
    collocations: ["een hoed dragen", "een hoed passen"],
    cefrLevel: "A2",
  },
  {
    lemma: "riem",
    article: "de",
    plural: "riemen",
    diminutive: "riempje",
    diminutivePlural: "riempjes",
    adjAgreement: { definite: "de leren riem", indefinite: "een leren riem" },
    collocations: ["een riem omdoen", "een riem strakker maken"],
    cefrLevel: "A2",
  },
  {
    lemma: "knoop",
    article: "de",
    plural: "knopen",
    diminutive: "knoopje",
    diminutivePlural: "knoopjes",
    adjAgreement: { definite: "de losse knoop", indefinite: "een losse knoop" },
    collocations: ["een knoop dichtmaken", "een knoop vastnaaien"],
    cefrLevel: "A2",
  },
  {
    lemma: "hoofd",
    article: "het",
    plural: "hoofden",
    diminutive: "hoofdje",
    diminutivePlural: "hoofdjes",
    adjAgreement: { definite: "het zware hoofd", indefinite: "een zwaar hoofd" },
    collocations: ["hoofdpijn hebben", "je hoofd stoten"],
    cefrLevel: "A2",
  },
  {
    lemma: "hand",
    article: "de",
    plural: "handen",
    diminutive: "handje",
    diminutivePlural: "handjes",
    adjAgreement: { definite: "de schone hand", indefinite: "een schone hand" },
    collocations: ["je handen wassen", "iemand een hand geven"],
    cefrLevel: "A2",
  },
  {
    lemma: "voet",
    article: "de",
    plural: "voeten",
    diminutive: "voetje",
    diminutivePlural: "voetjes",
    adjAgreement: { definite: "de koude voet", indefinite: "een koude voet" },
    collocations: ["te voet gaan", "je voeten warmen"],
    cefrLevel: "A2",
  },
  {
    lemma: "oog",
    article: "het",
    plural: "ogen",
    diminutive: "oogje",
    diminutivePlural: "oogjes",
    adjAgreement: { definite: "het bruine oog", indefinite: "een bruin oog" },
    collocations: ["een oogje in het zeil houden", "je ogen dichtdoen"],
    cefrLevel: "A2",
  },
  {
    lemma: "oor",
    article: "het",
    plural: "oren",
    diminutive: "oortje",
    diminutivePlural: "oortjes",
    adjAgreement: { definite: "het kleine oor", indefinite: "een klein oor" },
    collocations: ["oorpijn hebben", "iets in je oor fluisteren"],
    cefrLevel: "A2",
  },
  {
    lemma: "mond",
    article: "de",
    plural: "monden",
    diminutive: "mondje",
    diminutivePlural: "mondjes",
    adjAgreement: { definite: "de droge mond", indefinite: "een droge mond" },
    collocations: ["je mond spoelen", "iets in je mond nemen"],
    cefrLevel: "A2",
  },
  {
    lemma: "rug",
    article: "de",
    plural: "ruggen",
    diminutive: "rugje",
    diminutivePlural: "rugjes",
    adjAgreement: { definite: "de pijnlijke rug", indefinite: "een pijnlijke rug" },
    collocations: ["rugpijn hebben", "op je rug liggen"],
    cefrLevel: "A2",
  },
  {
    lemma: "buik",
    article: "de",
    plural: "buiken",
    diminutive: "buikje",
    diminutivePlural: "buikjes",
    adjAgreement: { definite: "de dikke buik", indefinite: "een dikke buik" },
    collocations: ["buikpijn hebben", "op je buik liggen"],
    cefrLevel: "A2",
  },
  {
    lemma: "arm",
    article: "de",
    plural: "armen",
    diminutive: "armpje",
    diminutivePlural: "armpjes",
    adjAgreement: { definite: "de sterke arm", indefinite: "een sterke arm" },
    collocations: ["je arm breken", "iemand een arm geven"],
    cefrLevel: "A2",
  },
  {
    lemma: "been",
    article: "het",
    plural: "benen",
    diminutive: "beentje",
    diminutivePlural: "beentjes",
    adjAgreement: { definite: "het lange been", indefinite: "een lang been" },
    collocations: ["je been breken", "je benen strekken"],
    cefrLevel: "A2",
  },
  {
    lemma: "maand",
    article: "de",
    plural: "maanden",
    diminutive: "maandje",
    diminutivePlural: "maandjes",
    adjAgreement: { definite: "de drukke maand", indefinite: "een drukke maand" },
    collocations: ["een maand huur betalen", "volgende maand beginnen"],
    cefrLevel: "A2",
  },
  {
    lemma: "week",
    article: "de",
    plural: "weken",
    diminutive: "weekje",
    diminutivePlural: "weekjes",
    adjAgreement: { definite: "de drukke week", indefinite: "een drukke week" },
    collocations: ["volgende week afspreken", "een week vakantie nemen"],
    cefrLevel: "A2",
  },
  {
    lemma: "uur",
    article: "het",
    plural: "uren",
    diminutive: "uurtje",
    diminutivePlural: "uurtjes",
    adjAgreement: { definite: "het lange uur", indefinite: "een lang uur" },
    collocations: ["een uur wachten", "op tijd komen op het afgesproken uur"],
    cefrLevel: "A2",
  },
  {
    lemma: "minuut",
    article: "de",
    plural: "minuten",
    diminutive: "minuutje",
    diminutivePlural: "minuutjes",
    adjAgreement: { definite: "de laatste minuut", indefinite: "een laatste minuut" },
    collocations: ["vijf minuten wachten", "op de laatste minuut komen"],
    cefrLevel: "A2",
  },
  {
    lemma: "seizoen",
    article: "het",
    plural: "seizoenen",
    diminutive: "seizoentje",
    diminutivePlural: "seizoentjes",
    adjAgreement: { definite: "het nieuwe seizoen", indefinite: "een nieuw seizoen" },
    collocations: ["een nieuw seizoen beginnen", "kleding voor elk seizoen"],
    cefrLevel: "B1",
  },
  {
    lemma: "regen",
    article: "de",
    plural: "regens",
    diminutive: "regentje",
    diminutivePlural: "regentjes",
    adjAgreement: { definite: "de harde regen", indefinite: "een harde regen" },
    collocations: ["in de regen lopen", "een paraplu tegen de regen"],
    cefrLevel: "A2",
  },
  {
    lemma: "zon",
    article: "de",
    plural: "zonnen",
    diminutive: "zonnetje",
    diminutivePlural: "zonnetjes",
    adjAgreement: { definite: "de warme zon", indefinite: "een warme zon" },
    collocations: ["in de zon zitten", "de zon schijnt"],
    cefrLevel: "A2",
  },
  {
    lemma: "wind",
    article: "de",
    plural: "winden",
    diminutive: "windje",
    diminutivePlural: "windjes",
    adjAgreement: { definite: "de koude wind", indefinite: "een koude wind" },
    collocations: ["harde wind buiten", "tegen de wind in fietsen"],
    cefrLevel: "A2",
  },
  {
    lemma: "wolk",
    article: "de",
    plural: "wolken",
    diminutive: "wolkje",
    diminutivePlural: "wolkjes",
    adjAgreement: { definite: "de grijze wolk", indefinite: "een grijze wolk" },
    collocations: ["donkere wolken zien", "wolken aan de lucht"],
    cefrLevel: "A2",
  },
  {
    lemma: "storm",
    article: "de",
    plural: "stormen",
    diminutive: "stormpje",
    diminutivePlural: "stormpjes",
    adjAgreement: { definite: "de zware storm", indefinite: "een zware storm" },
    collocations: ["een storm verwachten", "thuisblijven vanwege de storm"],
    cefrLevel: "B1",
  },
  {
    lemma: "fiets",
    article: "de",
    plural: "fietsen",
    diminutive: "fietsje",
    diminutivePlural: "fietsjes",
    adjAgreement: { definite: "de oude fiets", indefinite: "een oude fiets" },
    collocations: ["op de fiets stappen", "je fiets op slot zetten"],
    cefrLevel: "A2",
  },
  {
    lemma: "trein",
    article: "de",
    plural: "treinen",
    diminutive: "treintje",
    diminutivePlural: "treintjes",
    adjAgreement: { definite: "de drukke trein", indefinite: "een drukke trein" },
    collocations: ["de trein missen", "met de trein reizen"],
    cefrLevel: "A2",
  },
  {
    lemma: "bus",
    article: "de",
    plural: "bussen",
    diminutive: "busje",
    diminutivePlural: "busjes",
    adjAgreement: { definite: "de volle bus", indefinite: "een volle bus" },
    collocations: ["op de bus wachten", "de bus instappen"],
    cefrLevel: "A2",
  },
  {
    lemma: "vlucht",
    article: "de",
    plural: "vluchten",
    diminutive: "vluchtje",
    diminutivePlural: "vluchtjes",
    adjAgreement: { definite: "de lange vlucht", indefinite: "een lange vlucht" },
    collocations: ["een vlucht boeken", "een vlucht missen"],
    cefrLevel: "B1",
  },
  {
    lemma: "weg",
    article: "de",
    plural: "wegen",
    diminutive: "wegje",
    diminutivePlural: "wegjes",
    adjAgreement: { definite: "de drukke weg", indefinite: "een drukke weg" },
    collocations: ["de weg vragen", "de weg kwijt zijn"],
    cefrLevel: "A2",
  },
  {
    lemma: "straat",
    article: "de",
    plural: "straten",
    diminutive: "straatje",
    diminutivePlural: "straatjes",
    adjAgreement: { definite: "de rustige straat", indefinite: "een rustige straat" },
    collocations: ["de straat oversteken", "in dezelfde straat wonen"],
    cefrLevel: "A2",
  },
  {
    lemma: "brug",
    article: "de",
    plural: "bruggen",
    diminutive: "brugje",
    diminutivePlural: "brugjes",
    adjAgreement: { definite: "de hoge brug", indefinite: "een hoge brug" },
    collocations: ["over de brug fietsen", "de brug staat open"],
    cefrLevel: "A2",
  },
  {
    lemma: "station",
    article: "het",
    plural: "stations",
    diminutive: "stationnetje",
    diminutivePlural: "stationnetjes",
    adjAgreement: { definite: "het drukke station", indefinite: "een druk station" },
    collocations: ["naar het station lopen", "op het station wachten"],
    cefrLevel: "A2",
  },
  {
    lemma: "kaart",
    article: "de",
    plural: "kaarten",
    diminutive: "kaartje",
    diminutivePlural: "kaartjes",
    adjAgreement: { definite: "de geldige kaart", indefinite: "een geldige kaart" },
    collocations: ["een kaartje kopen", "de kaart inchecken"],
    cefrLevel: "A2",
  },
  {
    lemma: "rijbewijs",
    article: "het",
    plural: "rijbewijzen",
    diminutive: "rijbewijsje",
    diminutivePlural: "rijbewijsjes",
    adjAgreement: { definite: "het geldige rijbewijs", indefinite: "een geldig rijbewijs" },
    collocations: ["een rijbewijs halen", "je rijbewijs laten zien"],
    cefrLevel: "B1",
  },
  {
    lemma: "telefoon",
    article: "de",
    plural: "telefoons",
    diminutive: "telefoontje",
    diminutivePlural: "telefoontjes",
    adjAgreement: { definite: "de nieuwe telefoon", indefinite: "een nieuwe telefoon" },
    collocations: ["de telefoon opnemen", "iemand een telefoontje geven"],
    cefrLevel: "A2",
  },
  {
    lemma: "handtekening",
    article: "de",
    plural: "handtekeningen",
    diminutive: "handtekeninkje",
    diminutivePlural: "handtekeninkjes",
    adjAgreement: { definite: "de officiële handtekening", indefinite: "een officiële handtekening" },
    collocations: ["een handtekening zetten", "om een handtekening vragen"],
    cefrLevel: "B1",
  },
  {
    lemma: "vergunning",
    article: "de",
    plural: "vergunningen",
    diminutive: "vergunninkje",
    diminutivePlural: "vergunninkjes",
    adjAgreement: { definite: "de benodigde vergunning", indefinite: "een benodigde vergunning" },
    collocations: ["een vergunning aanvragen", "een vergunning krijgen"],
    cefrLevel: "B1",
  },
  {
    lemma: "uitkering",
    article: "de",
    plural: "uitkeringen",
    diminutive: "uitkeringkje",
    diminutivePlural: "uitkeringkjes",
    adjAgreement: { definite: "de maandelijkse uitkering", indefinite: "een maandelijkse uitkering" },
    collocations: ["een uitkering aanvragen", "een uitkering ontvangen"],
    cefrLevel: "B1",
  },
  {
    lemma: "loonstrook",
    article: "de",
    plural: "loonstroken",
    diminutive: "loonstrookje",
    diminutivePlural: "loonstrookjes",
    adjAgreement: { definite: "de laatste loonstrook", indefinite: "een laatste loonstrook" },
    collocations: ["de loonstrook controleren", "een loonstrook bewaren"],
    cefrLevel: "B1",
  },
  {
    lemma: "dienstverband",
    article: "het",
    plural: "dienstverbanden",
    diminutive: "dienstverbandje",
    diminutivePlural: "dienstverbandjes",
    adjAgreement: { definite: "het vaste dienstverband", indefinite: "een vast dienstverband" },
    collocations: ["een vast dienstverband krijgen", "in dienstverband werken"],
    cefrLevel: "B1",
  },
  {
    lemma: "proeftijd",
    article: "de",
    plural: "proeftijden",
    diminutive: "proeftijdje",
    diminutivePlural: "proeftijdjes",
    adjAgreement: { definite: "de korte proeftijd", indefinite: "een korte proeftijd" },
    collocations: ["een proeftijd afspreken", "de proeftijd doorstaan"],
    cefrLevel: "B1",
  },
  {
    lemma: "baas",
    article: "de",
    plural: "bazen",
    diminutive: "baasje",
    diminutivePlural: "baasjes",
    adjAgreement: { definite: "de strenge baas", indefinite: "een strenge baas" },
    collocations: ["met je baas praten", "iets aan de baas vragen"],
    cefrLevel: "A2",
  },
  {
    lemma: "kantoor",
    article: "het",
    plural: "kantoren",
    diminutive: "kantoortje",
    diminutivePlural: "kantoortjes",
    adjAgreement: { definite: "het moderne kantoor", indefinite: "een modern kantoor" },
    collocations: ["naar kantoor gaan", "op kantoor werken"],
    cefrLevel: "A2",
  },
  {
    lemma: "vergadering",
    article: "de",
    plural: "vergaderingen",
    diminutive: "vergaderinkje",
    diminutivePlural: "vergaderinkjes",
    adjAgreement: { definite: "de lange vergadering", indefinite: "een lange vergadering" },
    collocations: ["een vergadering plannen", "naar een vergadering gaan"],
    cefrLevel: "B1",
  },
  {
    lemma: "vriend",
    article: "de",
    plural: "vrienden",
    diminutive: "vriendje",
    diminutivePlural: "vriendjes",
    adjAgreement: { definite: "de goede vriend", indefinite: "een goede vriend" },
    collocations: ["een vriend maken", "met een vriend afspreken"],
    cefrLevel: "A2",
  },
  {
    lemma: "klas",
    article: "de",
    plural: "klassen",
    diminutive: "klasje",
    diminutivePlural: "klasjes",
    adjAgreement: { definite: "de volle klas", indefinite: "een volle klas" },
    collocations: ["in dezelfde klas zitten", "een nieuwe klas beginnen"],
    cefrLevel: "A2",
  },
  {
    lemma: "tas",
    article: "de",
    plural: "tassen",
    diminutive: "tasje",
    diminutivePlural: "tasjes",
    adjAgreement: { definite: "de zware tas", indefinite: "een zware tas" },
    collocations: ["een tas dragen", "iets in je tas doen"],
    cefrLevel: "A2",
  },
  {
    lemma: "hond",
    article: "de",
    plural: "honden",
    diminutive: "hondje",
    diminutivePlural: "hondjes",
    adjAgreement: { definite: "de lieve hond", indefinite: "een lieve hond" },
    collocations: ["een hond uitlaten", "een hond aaien"],
    cefrLevel: "A2",
  },
  {
    lemma: "pijn",
    article: "de",
    plural: "pijnen",
    diminutive: "pijntje",
    diminutivePlural: "pijntjes",
    adjAgreement: { definite: "de erge pijn", indefinite: "een erge pijn" },
    collocations: ["pijn hebben", "pijn voelen in je rug"],
    cefrLevel: "A2",
  },
  {
    lemma: "verband",
    article: "het",
    plural: "verbanden",
    diminutive: "verbandje",
    diminutivePlural: "verbandjes",
    adjAgreement: { definite: "het strakke verband", indefinite: "een strak verband" },
    collocations: ["een verband aanleggen", "een verband verwisselen"],
    cefrLevel: "A2",
  },
  {
    lemma: "pinpas",
    article: "de",
    plural: "pinpassen",
    diminutive: "pinpasje",
    diminutivePlural: "pinpasjes",
    adjAgreement: { definite: "de geldige pinpas", indefinite: "een geldige pinpas" },
    collocations: ["met de pinpas betalen", "je pinpas activeren"],
    cefrLevel: "A2",
  },
  {
    lemma: "apotheek",
    article: "de",
    plural: "apotheken",
    diminutive: "apotheekje",
    diminutivePlural: "apotheekjes",
    adjAgreement: { definite: "de dichtstbijzijnde apotheek", indefinite: "een dichtstbijzijnde apotheek" },
    collocations: ["naar de apotheek gaan", "medicijnen ophalen bij de apotheek"],
    cefrLevel: "B1",
  },
  {
    lemma: "premie",
    article: "de",
    plural: "premies",
    diminutive: "premietje",
    diminutivePlural: "premietjes",
    adjAgreement: { definite: "de maandelijkse premie", indefinite: "een maandelijkse premie" },
    collocations: ["de premie betalen", "de premie verhogen"],
    cefrLevel: "B1",
  },
  {
    lemma: "krant",
    article: "de",
    plural: "kranten",
    diminutive: "krantje",
    diminutivePlural: "krantjes",
    adjAgreement: { definite: "de dagelijkse krant", indefinite: "een dagelijkse krant" },
    collocations: ["de krant lezen", "een krant kopen"],
    cefrLevel: "A2",
  },
];
