import { NounBundle } from "../types";

// §4 — sample of the SUBTLEX-NL × NT2Lex intersected core, stored as full
// noun bundles (never bare translation pairs). This is a seed slice, not
// the full ~2,000-5,000 lemma target from §4 — real authoring intersects
// SUBTLEX-NL frequency with NT2Lex CEFR grading and exam-domain vocabulary.
export const NOUN_BUNDLES: NounBundle[] = [
  {
    lemma: "huis",
    article: "het",
    plural: "huizen",
    diminutive: "huisje",
    diminutivePlural: "huisjes",
    adjAgreement: { definite: "het grote huis", indefinite: "een groot huis" },
    collocations: ["een huis kopen", "thuis zijn", "het huis uit gaan"],
    cefrLevel: "A2",
  },
  {
    lemma: "afspraak",
    article: "de",
    plural: "afspraken",
    diminutive: "afspraakje",
    diminutivePlural: "afspraakjes",
    adjAgreement: { definite: "de belangrijke afspraak", indefinite: "een belangrijke afspraak" },
    collocations: ["een afspraak maken", "een afspraak afzeggen", "op tijd komen voor een afspraak"],
    cefrLevel: "A2",
  },
  {
    lemma: "gemeente",
    article: "de",
    plural: "gemeenten",
    diminutive: "gemeentetje",
    diminutivePlural: "gemeentetjes",
    adjAgreement: { definite: "de lokale gemeente", indefinite: "een lokale gemeente" },
    collocations: ["je inschrijven bij de gemeente", "naar de gemeente gaan"],
    cefrLevel: "A2",
  },
  {
    lemma: "huisarts",
    article: "de",
    plural: "huisartsen",
    diminutive: "huisartsje",
    diminutivePlural: "huisartsjes",
    adjAgreement: { definite: "de nieuwe huisarts", indefinite: "een nieuwe huisarts" },
    collocations: ["een afspraak bij de huisarts", "je inschrijven bij een huisarts"],
    cefrLevel: "A2",
  },
  {
    lemma: "opleiding",
    article: "de",
    plural: "opleidingen",
    diminutive: "opleidinkje",
    diminutivePlural: "opleidinkjes",
    adjAgreement: { definite: "de moeilijke opleiding", indefinite: "een moeilijke opleiding" },
    collocations: ["een opleiding volgen", "een opleiding afmaken"],
    cefrLevel: "B1",
  },
  {
    lemma: "sollicitatie",
    article: "de",
    plural: "sollicitaties",
    diminutive: "sollicitatietje",
    diminutivePlural: "sollicitatietjes",
    adjAgreement: { definite: "de succesvolle sollicitatie", indefinite: "een succesvolle sollicitatie" },
    collocations: ["solliciteren naar een baan", "een sollicitatiebrief schrijven"],
    cefrLevel: "B1",
  },
  {
    lemma: "verzekering",
    article: "de",
    plural: "verzekeringen",
    diminutive: "verzekeringetje",
    diminutivePlural: "verzekeringetjes",
    adjAgreement: { definite: "de verplichte verzekering", indefinite: "een verplichte verzekering" },
    collocations: ["een verzekering afsluiten", "zorgverzekering betalen"],
    cefrLevel: "B1",
  },
  {
    lemma: "kind",
    article: "het",
    plural: "kinderen",
    diminutive: "kindje",
    diminutivePlural: "kindjes",
    adjAgreement: { definite: "het kleine kind", indefinite: "een klein kind" },
    collocations: ["kinderen opvoeden", "een kind krijgen"],
    cefrLevel: "A2",
  },
  {
    lemma: "baan",
    article: "de",
    plural: "banen",
    diminutive: "baantje",
    diminutivePlural: "baantjes",
    adjAgreement: { definite: "de goede baan", indefinite: "een goede baan" },
    collocations: ["een baan zoeken", "een baan vinden", "fulltime werken"],
    cefrLevel: "A2",
  },
  {
    lemma: "contract",
    article: "het",
    plural: "contracten",
    diminutive: "contractje",
    diminutivePlural: "contractjes",
    adjAgreement: { definite: "het nieuwe contract", indefinite: "een nieuw contract" },
    collocations: ["een contract tekenen", "een tijdelijk contract"],
    cefrLevel: "B1",
  },
  {
    lemma: "salaris",
    article: "het",
    plural: "salarissen",
    diminutive: "salarisje",
    diminutivePlural: "salarisjes",
    adjAgreement: { definite: "het hoge salaris", indefinite: "een hoog salaris" },
    collocations: ["salaris krijgen", "een goed salaris verdienen"],
    cefrLevel: "B1",
  },
  {
    lemma: "woning",
    article: "de",
    plural: "woningen",
    diminutive: "woninkje",
    diminutivePlural: "woninkjes",
    adjAgreement: { definite: "de kleine woning", indefinite: "een kleine woning" },
    collocations: ["een woning huren", "op zoek naar een woning"],
    cefrLevel: "A2",
  },
  {
    lemma: "buurt",
    article: "de",
    plural: "buurten",
    diminutive: "buurtje",
    diminutivePlural: "buurtjes",
    adjAgreement: { definite: "de rustige buurt", indefinite: "een rustige buurt" },
    collocations: ["in de buurt wonen", "een rustige buurt zoeken"],
    cefrLevel: "A2",
  },
  {
    lemma: "ziekenhuis",
    article: "het",
    plural: "ziekenhuizen",
    diminutive: "ziekenhuisje",
    diminutivePlural: "ziekenhuisjes",
    adjAgreement: { definite: "het grote ziekenhuis", indefinite: "een groot ziekenhuis" },
    collocations: ["naar het ziekenhuis gaan", "in het ziekenhuis liggen"],
    cefrLevel: "A2",
  },
  {
    lemma: "medicijn",
    article: "het",
    plural: "medicijnen",
    diminutive: "medicijntje",
    diminutivePlural: "medicijntjes",
    adjAgreement: { definite: "het sterke medicijn", indefinite: "een sterk medicijn" },
    collocations: ["medicijnen innemen", "medicijnen halen bij de apotheek"],
    cefrLevel: "A2",
  },
  {
    lemma: "school",
    article: "de",
    plural: "scholen",
    diminutive: "schooltje",
    diminutivePlural: "schooltjes",
    adjAgreement: { definite: "de goede school", indefinite: "een goede school" },
    collocations: ["naar school gaan", "een kind naar school brengen"],
    cefrLevel: "A2",
  },
  {
    lemma: "cursus",
    article: "de",
    plural: "cursussen",
    diminutive: "cursusje",
    diminutivePlural: "cursusjes",
    adjAgreement: { definite: "de nieuwe cursus", indefinite: "een nieuwe cursus" },
    collocations: ["een cursus volgen", "Nederlands leren via een cursus"],
    cefrLevel: "A2",
  },
  {
    lemma: "brief",
    article: "de",
    plural: "brieven",
    diminutive: "briefje",
    diminutivePlural: "briefjes",
    adjAgreement: { definite: "de belangrijke brief", indefinite: "een belangrijke brief" },
    collocations: ["een brief schrijven", "een brief ontvangen"],
    cefrLevel: "A2",
  },
  {
    lemma: "formulier",
    article: "het",
    plural: "formulieren",
    diminutive: "formuliertje",
    diminutivePlural: "formuliertjes",
    adjAgreement: { definite: "het lange formulier", indefinite: "een lang formulier" },
    collocations: ["een formulier invullen", "een formulier opsturen"],
    cefrLevel: "B1",
  },
  {
    lemma: "paspoort",
    article: "het",
    plural: "paspoorten",
    diminutive: "paspoortje",
    diminutivePlural: "paspoortjes",
    adjAgreement: { definite: "het geldige paspoort", indefinite: "een geldig paspoort" },
    collocations: ["een paspoort aanvragen", "je paspoort meenemen"],
    cefrLevel: "A2",
  },
];
