import { TargetLevel } from "../types";

export interface SpeakingPrompt {
  id: string;
  text: string;
  topic: string;
  level: TargetLevel;
  focusHintRu: string;
}

// §8 — elicited imitation as the cheap speaking proxy for placement and
// progress checks: read the target sentence aloud, then self-compare
// against your own recording. No ASR scoring — see README for why.
export const SPEAKING_PROMPTS: SpeakingPrompt[] = [
  {
    id: "sp-1",
    text: "Ik heb een afspraak bij de huisarts.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts' — это не русское [х].",
  },
  {
    id: "sp-2",
    text: "Kunt u mij een andere datum geven?",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на интонацию вежливого вопроса и позицию глагола 'kunt' в начале.",
  },
  {
    id: "sp-3",
    text: "Ik woon er sinds twee jaar en het bevalt me goed.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "'er' здесь заменяет место — потренируйте его слитное произношение с предыдущим словом.",
  },
  {
    id: "sp-4",
    text: "Kom maar binnen, het is koud buiten.",
    topic: "gesprek",
    level: "A2",
    focusHintRu: "Частица 'maar' произносится безударно и быстро — не выделяйте её как отдельное слово.",
  },
  {
    id: "sp-5",
    text: "Ik heb net een nieuwe baan gevonden bij een groot bedrijf.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Долгота гласных: 'baan' с долгим [aː], в отличие от короткого 'ban'.",
  },
  {
    id: "sp-6",
    text: "Ik ben mijn sleutel vergeten, kunt u de deur openmaken?",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Разделяемый глагол 'openmaken' — в устной речи оба элемента произносятся отдельно и чётко.",
  },
  {
    id: "sp-7",
    text: "Wachten jullie al lang op de dokter?",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "'wachten op' — устойчивый предлог, произносите как единый смысловой блок.",
  },
  {
    id: "sp-8",
    text: "Ik moet mijn rekening voor het einde van de maand betalen.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Финальное оглушение в 'rekening' — звучит на конце глухо, но пишется через -g.",
  },
  {
    id: "sp-9",
    text: "Heeft u een moment, ik wil graag iets vragen.",
    topic: "gesprek",
    level: "A2",
    focusHintRu: "Вежливая вводная фраза — интонация должна звучать мягко, не как требование.",
  },
  {
    id: "sp-10",
    text: "Ik volg een cursus Nederlands bij de gemeente, twee keer per week.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "/x/ в 'cursus' звучит иначе, чем в 'gemeente' — сравните позицию звука в слове.",
  },
  {
    id: "sp-11",
    text: "Kunt u mij helpen met het invullen van dit formulier?",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Долгий кластер согласных в 'invullen' — не глотайте средние звуки при быстрой речи.",
  },
  {
    id: "sp-12",
    text: "Mijn buurman is heel aardig, we drinken soms samen koffie.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Огублённый гласный в 'buurman' — не путайте с русским [у].",
  },
  {
    id: "sp-13",
    text: "Ik heb een nieuw adres, ik moet dat nog doorgeven aan de gemeente.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Разделяемый глагол 'doorgeven' — 'geven' спрягается, 'door' остаётся в конце.",
  },
  {
    id: "sp-14",
    text: "Ik heb een verzekering afgesloten voor mijn nieuwe woning.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Причастие 'afgesloten' — приставка 'ge-' встраивается внутрь разделяемого глагола.",
  },
  {
    id: "sp-15",
    text: "Ik ga morgen naar de tandarts, ik heb al twee weken kiespijn.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Долгий гласный в 'tandarts' vs короткий в похожих словах — следите за длительностью.",
  },

  // --- +100 batch: 10 sentences per topic (health, rescheduling, housing,
  // work, municipality, education, money, transport, family, neighborhood),
  // each topic sharing one pronunciation-focus hint for a specific
  // Russian-L1 trouble spot (guttural g/ch, ui/ei diphthongs, r, etc.).
  {
    id: "sp-gen-1",
    text: "Ik heb een afspraak bij de huisarts.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-2",
    text: "Mijn keel doet al twee dagen pijn.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-3",
    text: "Ik moet mijn medicijnen op tijd innemen.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-4",
    text: "De dokter heeft een recept voor mij geschreven.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-5",
    text: "Ik voel me vandaag niet zo goed.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-6",
    text: "Kunt u mij doorverwijzen naar een specialist?",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-7",
    text: "Ik ben allergisch voor bepaalde medicijnen.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-8",
    text: "De tandarts controleert mijn tanden elk jaar.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-9",
    text: "Ik heb een verband om mijn arm.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-10",
    text: "De apotheek is om vijf uur gesloten.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Следите за /x/ в 'huisarts'/'gezondheid' — это не русское [х], звук образуется глубже, у корня языка.",
  },
  {
    id: "sp-gen-11",
    text: "Kunt u mij een andere datum geven?",
    topic: "afspraak_verzetten",
    level: "B1",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-12",
    text: "Ik kan helaas niet op de afgesproken tijd komen.",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-13",
    text: "Zou het mogelijk zijn om te verzetten naar volgende week?",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-14",
    text: "Ik moet mijn afspraak van morgen annuleren.",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-15",
    text: "Wanneer heeft u een andere plek vrij?",
    topic: "afspraak_verzetten",
    level: "B1",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-16",
    text: "Ik wil graag een nieuwe afspraak maken.",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-17",
    text: "Kan de afspraak een uur later beginnen?",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-18",
    text: "Ik ben helaas verhinderd op die dag.",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-19",
    text: "Is het mogelijk om vandaag nog langs te komen?",
    topic: "afspraak_verzetten",
    level: "B1",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-20",
    text: "Ik bel u terug zodra ik weet wanneer het uitkomt.",
    topic: "afspraak_verzetten",
    level: "A2",
    focusHintRu: "Обратите внимание на порядок слов в вопросе — глагол 'kunt' стоит в самом начале.",
  },
  {
    id: "sp-gen-21",
    text: "Ik zoek een huis met twee slaapkamers.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-22",
    text: "De huur van mijn woning gaat volgend jaar omhoog.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-23",
    text: "Mijn sleutel past niet meer op de voordeur.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-24",
    text: "De verwarming in mijn huis werkt niet goed.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-25",
    text: "Ik moet mijn adres wijzigen bij de gemeente.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-26",
    text: "Onze tuin is klein maar heel gezellig.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-27",
    text: "De verhuurder komt morgen langs voor onderhoud.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-28",
    text: "Ik woon al vijf jaar in dezelfde straat.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-29",
    text: "Het balkon is helaas aan de noordkant.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-30",
    text: "Wij zoeken een groter appartement voor onze familie.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Тренируйте дифтонг /œy/ в 'huis' и 'sleutel' — губы округлены сильнее, чем в русском 'ой'.",
  },
  {
    id: "sp-gen-31",
    text: "Ik heb morgen een sollicitatiegesprek.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-32",
    text: "Mijn contract loopt aan het eind van de maand af.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-33",
    text: "Ik werk fulltime bij een groot bedrijf.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-34",
    text: "Mijn salaris wordt elke maand op tijd betaald.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-35",
    text: "Ik zoek een baan die beter bij mij past.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-36",
    text: "Mijn baas is heel tevreden over mijn werk.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-37",
    text: "Ik heb een proeftijd van twee maanden.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-38",
    text: "Volgende week heb ik een belangrijke vergadering.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-39",
    text: "Ik wil graag meer uren per week werken.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-40",
    text: "Mijn collega's zijn erg behulpzaam.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Звук /sx/ в 'sollicitatie' и 'gesprek' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen-41",
    text: "Ik moet mij inschrijven bij de gemeente.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-42",
    text: "Kunt u mij helpen met dit formulier?",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-43",
    text: "Ik heb een nieuw paspoort nodig.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-44",
    text: "Mijn identiteitsbewijs is helaas verlopen.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-45",
    text: "Waar kan ik een uittreksel aanvragen?",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-46",
    text: "Ik heb een brief van de gemeente ontvangen.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-47",
    text: "De gemeentebalie is alleen op afspraak open.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-48",
    text: "Ik wil een verklaring van inschrijving aanvragen.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-49",
    text: "Mijn handtekening moet nog op het formulier.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-50",
    text: "Ik heb een vergunning nodig voor de verbouwing.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Тренируйте твёрдый начальный 'g' в 'gemeente' — гортанный звук, не русское [г].",
  },
  {
    id: "sp-gen-51",
    text: "Ik volg elke week twee lessen Nederlands.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-52",
    text: "Mijn kind gaat volgend jaar naar school.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-53",
    text: "Ik wil graag een cursus Nederlands volgen.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-54",
    text: "De docent legt de grammatica heel duidelijk uit.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-55",
    text: "Ik heb morgen een toets over de sterke werkwoorden.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-56",
    text: "Mijn klas bestaat uit twaalf studenten.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-57",
    text: "Ik moet nog veel woorden leren voor het examen.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-58",
    text: "De opleiding duurt in totaal twee jaar.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-59",
    text: "Ik oefen elke dag met luisteren en spreken.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-60",
    text: "Onze leraar geeft veel huiswerk mee.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /eː/ в 'les' и 'school' произносится длиннее, чем русское 'е'.",
  },
  {
    id: "sp-gen-61",
    text: "Ik moet deze maand nog een rekening betalen.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-62",
    text: "Mijn salaris komt elke maand op dezelfde dag binnen.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-63",
    text: "Ik heb een korting gekregen op mijn verzekering.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-64",
    text: "De premie voor mijn zorgverzekering gaat omhoog.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-65",
    text: "Ik spaar elke maand een klein bedrag.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-66",
    text: "Kunt u mij een factuur sturen?",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-67",
    text: "Ik betaal het liefst met mijn pinpas.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-68",
    text: "Mijn bankrekening staat al even in het rood.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-69",
    text: "Ik wil graag een betalingsregeling afspreken.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-70",
    text: "De prijs van boodschappen is dit jaar flink gestegen.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Звук /r/ в 'rekening' — раскатистый, произносится ближе к горлу, не как русское 'р'.",
  },
  {
    id: "sp-gen-71",
    text: "Ik ga elke dag met de fiets naar mijn werk.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-72",
    text: "De trein naar Utrecht vertrekt over tien minuten.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-73",
    text: "Ik heb de bus net gemist.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-74",
    text: "Mijn rijbewijs is nog drie jaar geldig.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-75",
    text: "Ik reis meestal met het openbaar vervoer.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-76",
    text: "De weg naar het station is best druk vandaag.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-77",
    text: "Ik moet nog een treinkaartje kopen.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-78",
    text: "Mijn fiets staat bij het station op slot.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-79",
    text: "Wij nemen morgen de auto naar de kust.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-80",
    text: "Ik sta al twintig minuten in de file.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Тренируйте начальный 'f' в 'fiets' — чёткий, без озвончения, как в 'фото'.",
  },
  {
    id: "sp-gen-81",
    text: "Mijn broer woont in een andere stad.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-82",
    text: "Onze dochter gaat volgend jaar trouwen.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-83",
    text: "Ik ga elk weekend op bezoek bij mijn ouders.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-84",
    text: "Mijn zoon is nog erg klein.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-85",
    text: "Wij vieren morgen de verjaardag van mijn oma.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-86",
    text: "Mijn zus werkt in het ziekenhuis.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-87",
    text: "Onze buurvrouw helpt vaak met de kinderen.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-88",
    text: "Ik bel mijn opa elke zondag.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-89",
    text: "Mijn neef komt volgende maand op bezoek.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-90",
    text: "Wij hebben een grote familie met veel neven en nichten.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trouwen' и 'klein' — начинается с открытого 'э', скользит к 'и'.",
  },
  {
    id: "sp-gen-91",
    text: "Onze buurt is heel rustig en groen.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-92",
    text: "Ik ken bijna al mijn buren goed.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-93",
    text: "Er is volgende week een buurtbijeenkomst.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-94",
    text: "Het buurthuis organiseert elke week iets leuks.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-95",
    text: "Ik doe vaak boodschappen bij de winkel om de hoek.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-96",
    text: "Onze straat wordt binnenkort opnieuw geasfalteerd.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-97",
    text: "Ik geniet van de rust in mijn buurt.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-98",
    text: "Er is een klein park vlak bij mijn huis.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-99",
    text: "Ik help soms mee met het schoonhouden van de buurt.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen-100",
    text: "De markt in onze buurt is elke zaterdag open.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Тренируйте безударное 'e' в 'buurt' и 'buurthuis' — короткий нейтральный звук [ə].",
  },
  {
    id: "sp-gen3-1",
    text: "Ik heb hoofdpijn en moet een afspraak maken bij de huisarts.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Звук /x/ в 'huisarts' образуется в глубине рта — не в горле, как русское [х], и не как немецкое [ch].",
  },
  {
    id: "sp-gen3-2",
    text: "Mijn dochter heeft koorts en blijft vandaag thuis.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "В 'dochter' звук /x/ следует сразу после короткой 'o' — не смягчайте его.",
  },
  {
    id: "sp-gen3-3",
    text: "De huisarts heeft mij doorverwezen naar het ziekenhuis.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Долгий гласный /iː/ в 'ziekenhuis' — тяните звук дольше, чем в русском 'и'.",
  },
  {
    id: "sp-gen3-4",
    text: "Ik moet mijn bloeddruk laten controleren.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Двойная 'd' в 'bloeddruk' произносится как один долгий звук, не как два отдельных.",
  },
  {
    id: "sp-gen3-5",
    text: "Ik heb een pil vergeten in te nemen vanmorgen.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Короткая 'i' в 'pil' — звук напряжённее и короче русского 'и'.",
  },
  {
    id: "sp-gen3-6",
    text: "De verpleegkundige prikt mijn arm voor een bloedtest.",
    topic: "gezondheid",
    level: "B1",
    focusHintRu: "Основное ударение в 'verpleegkundige' падает на третий слог — 'kun', а не на первый.",
  },
  {
    id: "sp-gen3-7",
    text: "Ik voel me duizelig als ik snel opsta.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Дифтонг /œy/ в 'duizelig' — губы округлены сильнее, чем в русском 'уй'.",
  },
  {
    id: "sp-gen3-8",
    text: "Mijn oor doet pijn sinds gisteren.",
    topic: "gezondheid",
    level: "A2",
    focusHintRu: "Безударное 'e' в 'gisteren' сводится к нейтральному звуку [ə], не проговаривайте его чётко.",
  },
  {
    id: "sp-gen3-9",
    text: "Ik moet mijn paspoort verlengen bij de gemeente.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Ударение в 'paspoort' на первом слоге, а долгий 'oo' произносится отчётливо на втором.",
  },
  {
    id: "sp-gen3-10",
    text: "Kunt u mij vertellen waar ik een parkeervergunning kan aanvragen?",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Согласный кластер 'rkeervergunning' — проговаривайте каждый звук чётко, не сокращайте.",
  },
  {
    id: "sp-gen3-11",
    text: "Ik ben verhuisd en moet mij opnieuw inschrijven.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Дифтонг /œy/ в 'verhuisd' — губы округляются, звук отличается от русского 'уй'.",
  },
  {
    id: "sp-gen3-12",
    text: "De ambtenaar vroeg om een kopie van mijn identiteitsbewijs.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Кластер 'mbt' в 'ambtenaar' — 'b' произносится очень слабо, почти неслышно.",
  },
  {
    id: "sp-gen3-13",
    text: "Ik wacht al een half uur op mijn nummer bij het loket.",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "Ударение в 'loket' падает на второй слог — lo-KET, а не на первый.",
  },
  {
    id: "sp-gen3-14",
    text: "Mijn rijbewijs moet ik persoonlijk ophalen bij het gemeentehuis.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "В 'rijbewijs' дифтонг /ɛi/ встречается дважды — следите, чтобы оба звучали одинаково.",
  },
  {
    id: "sp-gen3-15",
    text: "Ik heb een klacht ingediend over de vuilnisophaal.",
    topic: "gemeente",
    level: "B1",
    focusHintRu: "Звук /x/ в 'klacht' стоит после долгой 'a' — не забывайте про гортанное произношение.",
  },
  {
    id: "sp-gen3-16",
    text: "Waar kan ik mijn huisvuil kwijt op zaterdag?",
    topic: "gemeente",
    level: "A2",
    focusHintRu: "В 'huisvuil' дифтонг /œy/ повторяется дважды — тренируйте одинаковое округление губ.",
  },
  {
    id: "sp-gen3-17",
    text: "Ik moet morgen vroeg beginnen op mijn werk.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Ударение в 'beginnen' на втором слоге — be-GIN-nen.",
  },
  {
    id: "sp-gen3-18",
    text: "Mijn leidinggevende heeft mijn functioneren besproken.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Длинное слово 'leidinggevende' имеет главное ударение на первом слоге, остальные — слабее.",
  },
  {
    id: "sp-gen3-19",
    text: "Ik werk parttime, drie dagen in de week.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Английское заимствование 'parttime' произносится на голландский манер, с твёрдым 't'.",
  },
  {
    id: "sp-gen3-20",
    text: "Ik heb een uitzendbureau gebeld voor een tijdelijke baan.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Дифтонг /œy/ в 'uitzendbureau' плюс французское ударение на 'bureau' — на последний слог.",
  },
  {
    id: "sp-gen3-21",
    text: "Mijn werkgever betaalt mijn reiskosten volledig.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'reiskosten' — начинайте с открытого 'э' и скользите к 'и'.",
  },
  {
    id: "sp-gen3-22",
    text: "Ik moet overwerken omdat we een deadline hebben.",
    topic: "werk",
    level: "B1",
    focusHintRu: "Заимствование 'deadline' сохраняет английское произношение — не читайте его по голландским правилам.",
  },
  {
    id: "sp-gen3-23",
    text: "Ik heb morgen een dag vrij genomen.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Долгий дифтонг /ɛi/ в 'vrij' — растягивайте звук чуть дольше обычного.",
  },
  {
    id: "sp-gen3-24",
    text: "Mijn werkplek ligt vlak bij het station.",
    topic: "werk",
    level: "A2",
    focusHintRu: "Кластер согласных 'rkpl' в 'werkplek' — проговаривайте все звуки, не сливайте их.",
  },
  {
    id: "sp-gen3-25",
    text: "Wij hebben net een nieuwe woonkamer geschilderd.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Сочетание /sx/ в 'geschilderd' — сначала мягкий 's', потом гортанный 'ch'.",
  },
  {
    id: "sp-gen3-26",
    text: "Ons huurcontract loopt over drie maanden af.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Долгая огублённая 'uu' в 'huurcontract' — не путайте с русским 'у'.",
  },
  {
    id: "sp-gen3-27",
    text: "De buren boven ons maken 's avonds veel lawaai.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Долгая 'uu' в 'buren' и безударное 'e' в 'avonds' звучат по-разному — не смешивайте их.",
  },
  {
    id: "sp-gen3-28",
    text: "Ik moet de vuilnisbak nog buiten zetten.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Дифтонг /œy/ повторяется в 'vuilnisbak' и 'buiten' — тренируйте одинаковое произношение.",
  },
  {
    id: "sp-gen3-29",
    text: "Mijn slaapkamer is klein maar licht.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Долгая 'aa' в 'slaapkamer' — звук длиннее, чем в коротком 'a'.",
  },
  {
    id: "sp-gen3-30",
    text: "Wij wonen op de derde verdieping zonder lift.",
    topic: "wonen",
    level: "A2",
    focusHintRu: "Долгий гласный /iː/ в 'verdieping' — тяните звук отчётливо.",
  },
  {
    id: "sp-gen3-31",
    text: "De verwarmingsketel moet dit jaar vervangen worden.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Длинный кластер согласных в 'verwarmingsketel' — не глотайте средние слоги.",
  },
  {
    id: "sp-gen3-32",
    text: "Ik heb een lekkage in de badkamer ontdekt.",
    topic: "wonen",
    level: "B1",
    focusHintRu: "Двойная 'kk' в 'lekkage' делает предыдущую 'e' короткой — не растягивайте её.",
  },
  {
    id: "sp-gen3-33",
    text: "Mijn moeder belt mij elke avond even op.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Короткая 'e' в 'belt' — звук короче и напряжённее русского 'э'.",
  },
  {
    id: "sp-gen3-34",
    text: "Mijn schoonouders komen dit weekend logeren.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Кластер 'sch' в 'schoonouders' произносится как /sx/, а не как русское 'ш'.",
  },
  {
    id: "sp-gen3-35",
    text: "Ik breng mijn kinderen elke ochtend naar school.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Звук /x/ в 'ochtend' стоит после короткой 'o' — произносите его глубоко в горле.",
  },
  {
    id: "sp-gen3-36",
    text: "Mijn oudste zoon studeert nu in een andere stad.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Ударение в 'studeert' падает на второй слог — stu-DEERT.",
  },
  {
    id: "sp-gen3-37",
    text: "Wij eten elke zondag samen bij mijn ouders.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Носовой звук в 'zondag' — 'n' перед 'd' произносится слитно с гласной.",
  },
  {
    id: "sp-gen3-38",
    text: "Mijn tante woont al jaren in het buitenland.",
    topic: "familie",
    level: "B1",
    focusHintRu: "Дифтонг /œy/ в 'buitenland' — губы округлены сильнее, чем при русском 'уй'.",
  },
  {
    id: "sp-gen3-39",
    text: "Ik pas dit weekend op mijn kleine neefje.",
    topic: "familie",
    level: "A2",
    focusHintRu: "Уменьшительный суффикс '-je' в 'neefje' произносится как отдельный слог с приглушённым звуком.",
  },
  {
    id: "sp-gen3-40",
    text: "Ik moet nog snel wat boodschappen doen voor het avondeten.",
    topic: "boodschappen",
    level: "A2",
    focusHintRu: "Долгая 'oo' и сочетание /sx/ в 'boodschappen' — не сокращайте гласную перед 'sch'.",
  },
  {
    id: "sp-gen3-41",
    text: "Kunt u mij zeggen waar de melk staat?",
    topic: "boodschappen",
    level: "A2",
    focusHintRu: "Короткая 'e' в 'zeggen' — звук отличается от долгого 'ee', не растягивайте его.",
  },
  {
    id: "sp-gen3-42",
    text: "Ik ben mijn boodschappenlijstje thuis vergeten.",
    topic: "boodschappen",
    level: "B1",
    focusHintRu: "В длинном слове 'boodschappenlijstje' главное ударение падает на первый слог.",
  },
  {
    id: "sp-gen3-43",
    text: "De winkel is helaas al gesloten op zondag.",
    topic: "boodschappen",
    level: "A2",
    focusHintRu: "Долгая 'o' в 'gesloten' — звук более закрытый и долгий, чем русское 'о'.",
  },
  {
    id: "sp-gen3-44",
    text: "Ik zoek een korting op deze producten.",
    topic: "boodschappen",
    level: "B1",
    focusHintRu: "Короткая 'o' в 'korting' — звук более открытый, чем русское 'о'.",
  },
  {
    id: "sp-gen3-45",
    text: "Mag ik met mijn pinpas betalen?",
    topic: "boodschappen",
    level: "A2",
    focusHintRu: "Короткая 'i' в 'pinpas' — звук напряжённее и короче русского 'и'.",
  },
  {
    id: "sp-gen3-46",
    text: "Ik heb te veel groente en fruit gekocht.",
    topic: "boodschappen",
    level: "A2",
    focusHintRu: "Гласная 'oe' в 'groente' произносится как звук, близкий к русскому 'у', но короче.",
  },
  {
    id: "sp-gen3-47",
    text: "De rij bij de kassa was ontzettend lang.",
    topic: "boodschappen",
    level: "B1",
    focusHintRu: "Дифтонг /ɛi/ в 'rij' и короткая 'a' в 'kassa' — не путайте длительность этих гласных.",
  },
  {
    id: "sp-gen3-48",
    text: "De bus komt vandaag vijf minuten te laat.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Короткая 'u' в 'bus' произносится иначе, чем долгая 'uu' в похожих словах.",
  },
  {
    id: "sp-gen3-49",
    text: "Ik moet nog een OV-chipkaart opladen.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Заимствованное 'chip' произносится с английским звуком, не как голландское /sx/.",
  },
  {
    id: "sp-gen3-50",
    text: "Mijn trein heeft een kwartier vertraging.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Дифтонг /ɛi/ в 'trein' — скользите от открытого 'э' к 'и'.",
  },
  {
    id: "sp-gen3-51",
    text: "Ik parkeer mijn auto meestal in de garage.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Слово 'garage' — французское заимствование, ударение на последнем слоге.",
  },
  {
    id: "sp-gen3-52",
    text: "Wij fietsen elke ochtend samen naar het werk.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Долгий гласный /iː/ в 'fietsen' — тяните звук дольше обычного.",
  },
  {
    id: "sp-gen3-53",
    text: "Ik heb mijn OV-kaart niet bij me.",
    topic: "vervoer",
    level: "A2",
    focusHintRu: "Безударное 'me' в конце фразы редуцируется до нейтрального звука.",
  },
  {
    id: "sp-gen3-54",
    text: "De weg was afgesloten vanwege werkzaamheden.",
    topic: "vervoer",
    level: "B1",
    focusHintRu: "Приставка 'af-' в 'afgesloten' встраивается перед корнем причастия — произносите её отдельно.",
  },
  {
    id: "sp-gen3-55",
    text: "Onze buurtsuper is dag en nacht open.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Долгая огублённая 'uu' в 'buurtsuper' отличается от русского 'у'.",
  },
  {
    id: "sp-gen3-56",
    text: "Ik heb de nieuwe buren nog niet ontmoet.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Долгая 'uu' в 'buren' — звук образуется с округлёнными губами, как немецкое ü.",
  },
  {
    id: "sp-gen3-57",
    text: "Er hangt een nieuwe brievenbus bij de ingang.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Долгая /iː/ в 'brievenbus' контрастирует с короткой 'u' во втором слове.",
  },
  {
    id: "sp-gen3-58",
    text: "De straatverlichting is sinds gisteren kapot.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Составное слово 'straatverlichting' — основное ударение на первом элементе.",
  },
  {
    id: "sp-gen3-59",
    text: "Ik doe mee aan de opruimactie in de buurt.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Дифтонг /œy/ в 'opruimactie' — тренируйте округление губ.",
  },
  {
    id: "sp-gen3-60",
    text: "Het speeltuintje bij ons huis is net vernieuwd.",
    topic: "buurt",
    level: "A2",
    focusHintRu: "Уменьшительный суффикс '-tje' в 'speeltuintje' произносится отдельно, с глухим 't'.",
  },
  {
    id: "sp-gen3-61",
    text: "Onze buurtbewoners organiseren een straatfeest.",
    topic: "buurt",
    level: "B1",
    focusHintRu: "Длинное слово 'buurtbewoners' — долгая 'uu' в начале, ударение на первом слоге.",
  },
  {
    id: "sp-gen3-62",
    text: "Ik ga elk weekend hardlopen in het park.",
    topic: "vrije_tijd",
    level: "A2",
    focusHintRu: "Составной глагол 'hardlopen' — оба элемента произносятся с равным весом.",
  },
  {
    id: "sp-gen3-63",
    text: "Mijn hobby is schilderen, ik doe het elke week.",
    topic: "vrije_tijd",
    level: "B1",
    focusHintRu: "Сочетание /sx/ в 'schilderen' — 's' мягкий, за ним следует гортанный 'ch'.",
  },
  {
    id: "sp-gen3-64",
    text: "Wij spelen zaterdag een potje voetbal.",
    topic: "vrije_tijd",
    level: "A2",
    focusHintRu: "Короткая 'o' в 'potje' произносится более открыто, чем русское 'о'.",
  },
  {
    id: "sp-gen3-65",
    text: "Ik lees graag een boek voor het slapengaan.",
    topic: "vrije_tijd",
    level: "A2",
    focusHintRu: "Долгий гласный 'oe' в 'boek' — звук ближе к русскому 'у', но более закрытый.",
  },
  {
    id: "sp-gen3-66",
    text: "Mijn vrienden en ik gaan zondag naar de bioscoop.",
    topic: "vrije_tijd",
    level: "B1",
    focusHintRu: "Долгая 'oo' в 'bioscoop' — произносите её отчётливо на последнем слоге.",
  },
  {
    id: "sp-gen3-67",
    text: "Ik zwem twee keer per week in het buurtbad.",
    topic: "vrije_tijd",
    level: "B1",
    focusHintRu: "Долгая огублённая 'uu' в 'buurtbad' — не сокращайте её до короткого звука.",
  },
  {
    id: "sp-gen3-68",
    text: "Wij gaan deze zomer kamperen in Frankrijk.",
    topic: "vrije_tijd",
    level: "A2",
    focusHintRu: "Заимствованное 'kamperen' произносится с голландским ударением на первом слоге.",
  },
  {
    id: "sp-gen3-69",
    text: "Ik speel gitaar in mijn vrije tijd.",
    topic: "vrije_tijd",
    level: "A2",
    focusHintRu: "Ударение в 'gitaar' падает на последний слог — gi-TAAR, с долгой 'aa'.",
  },
  {
    id: "sp-gen3-70",
    text: "Ik moet nog mijn belastingaangifte invullen.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Долгая 'aa' в 'aangifte' — звук значительно длиннее короткой 'a'.",
  },
  {
    id: "sp-gen3-71",
    text: "Ik heb geld geleend van mijn broer.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Короткая 'e' в 'geld' — не путайте с долгим 'ee' в похожих словах.",
  },
  {
    id: "sp-gen3-72",
    text: "Mijn spaarrekening staat bijna leeg.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Долгая 'aa' в 'spaarrekening' контрастирует с короткой 'e' далее в слове.",
  },
  {
    id: "sp-gen3-73",
    text: "Ik betaal mijn huur altijd aan het begin van de maand.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Долгая огублённая 'uu' в 'huur' — губы округлены, звук близок к немецкому ü.",
  },
  {
    id: "sp-gen3-74",
    text: "De bank heeft mijn pinpas geblokkeerd.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Причастие 'geblokkeerd' — ударение на предпоследнем слоге, долгая 'ee'.",
  },
  {
    id: "sp-gen3-75",
    text: "Ik moet nog een lening aanvragen voor de verbouwing.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Долгая 'e' в 'lening' — звук более закрытый, чем в коротком 'e'.",
  },
  {
    id: "sp-gen3-76",
    text: "Mijn energierekening is dit kwartaal veel hoger.",
    topic: "geld",
    level: "B1",
    focusHintRu: "Составное слово 'energierekening' — главное ударение на первом элементе.",
  },
  {
    id: "sp-gen3-77",
    text: "Ik heb een korting gekregen op mijn abonnement.",
    topic: "geld",
    level: "A2",
    focusHintRu: "Слово 'abonnement' — французское заимствование, ударение на последнем слоге.",
  },
  {
    id: "sp-gen3-78",
    text: "Mijn dochter zit in groep vijf van de basisschool.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Сочетание /sx/ в 'basisschool' — не смягчайте 'ch' до русского 'ш'.",
  },
  {
    id: "sp-gen3-79",
    text: "Ik volg een taalcursus op maandag en woensdag.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Долгая 'aa' в 'taalcursus' — звук длиннее, чем в коротком 'a'.",
  },
  {
    id: "sp-gen3-80",
    text: "De leraar geeft extra uitleg na de les.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Дифтонг /œy/ в 'uitleg' — тренируйте округление губ, как в 'huis'.",
  },
  {
    id: "sp-gen3-81",
    text: "Ik moet mij inschrijven voor het examen Nederlands.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Ударение в 'examen' падает на второй слог — ex-A-men.",
  },
  {
    id: "sp-gen3-82",
    text: "Mijn zoon heeft moeite met de grammaticaregels.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Длинное составное слово 'grammaticaregels' — не глотайте средние слоги при произношении.",
  },
  {
    id: "sp-gen3-83",
    text: "Ik oefen mijn uitspraak elke avond hardop.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Дифтонг /œy/ в 'uitspraak' и долгая 'aa' в том же слове — тренируйте оба звука.",
  },
  {
    id: "sp-gen3-84",
    text: "De schoolvakantie begint volgende week vrijdag.",
    topic: "onderwijs",
    level: "A2",
    focusHintRu: "Сочетание /sx/ в 'school' и дифтонг /ɛi/ в 'vrijdag' — два разных звука в одной фразе.",
  },
  {
    id: "sp-gen3-85",
    text: "Ik haal mijn diploma aan het eind van dit jaar.",
    topic: "onderwijs",
    level: "B1",
    focusHintRu: "Долгая 'o' в 'diploma' — ударение падает на второй слог, di-PLO-ma.",
  },
];
