// Generated by scripts/content-pipeline.mjs from content/sources/speaking-exam.json. Do not edit directly.

export interface SpeakingExamItem {
  id: string;
  text: string;
  topic: string;
  timeLimitS: 20 | 30;
}

// Original prompts for the signal-paced Spreken demo. The source document
// records provenance and editorial review state without shipping that metadata
// in the learner bundle. The pool contains at least 8 short and 8 medium items.
export const SPEAKING_EXAM_ITEMS: SpeakingExamItem[] = [
  { id: "sexam-1", topic: "gezondheid", timeLimitS: 20, text: "Vertel kort waarom u vandaag naar de huisarts gaat." },
  { id: "sexam-2", topic: "gemeente", timeLimitS: 30, text: "Leg uit welke documenten u nodig heeft om u in te schrijven bij de gemeente." },
  { id: "sexam-3", topic: "werk", timeLimitS: 20, text: "Vertel kort wat voor werk u zoekt." },
  { id: "sexam-4", topic: "wonen", timeLimitS: 30, text: "Beschrijf uw woning en waarom u daar graag woont." },
  { id: "sexam-5", topic: "afspraak_verzetten", timeLimitS: 20, text: "Leg uit waarom u een afspraak wilt verzetten." },
  { id: "sexam-6", topic: "onderwijs", timeLimitS: 30, text: "Vertel waarom u een cursus Nederlands volgt." },
  { id: "sexam-7", topic: "geld", timeLimitS: 20, text: "Leg kort uit hoe u uw rekeningen betaalt." },
  { id: "sexam-8", topic: "buurt", timeLimitS: 30, text: "Vertel iets over uw buurt en uw buren." },
  { id: "sexam-9", topic: "gezondheid", timeLimitS: 20, text: "Beschrijf kort uw klachten aan de dokter." },
  { id: "sexam-10", topic: "werk", timeLimitS: 30, text: "Vertel over uw laatste sollicitatiegesprek." },
  { id: "sexam-11", topic: "documenten", timeLimitS: 20, text: "Leg uit welk document u bij de gemeente wilt aanvragen." },
  { id: "sexam-12", topic: "wonen", timeLimitS: 30, text: "Leg uit wat u zou doen als de verwarming in uw huis stuk is." },
  { id: "sexam-13", topic: "dagelijks_leven", timeLimitS: 20, text: "Vertel kort over uw dagelijkse routine." },
  { id: "sexam-14", topic: "gemeente", timeLimitS: 30, text: "Leg uit wat u zou zeggen als u een fout in een brief van de gemeente vindt." },
  { id: "sexam-15", topic: "werk", timeLimitS: 20, text: "Vertel kort waarom u geschikt bent voor een baan." },
  { id: "sexam-16", topic: "geld", timeLimitS: 30, text: "Leg uit wat u zou doen als er een fout op uw rekening staat." },
  { id: "sexam-17", topic: "onderwijs", timeLimitS: 20, text: "Vertel kort welke cursus u nu volgt of zou willen volgen." },
  { id: "sexam-18", topic: "gezondheid", timeLimitS: 30, text: "Leg uit wat u zou doen als u een afspraak bij de dokter wilt verzetten." },
  { id: "sexam-19", topic: "vervoer", timeLimitS: 20, text: "Vertel kort hoe u meestal naar uw werk of school reist." },
  { id: "sexam-20", topic: "documenten", timeLimitS: 30, text: "Beschrijf welke stappen u zou nemen om een verlopen paspoort te vernieuwen." },
  { id: "sexam-21", topic: "vrije_tijd", timeLimitS: 20, text: "Vertel kort wat u het liefst doet in uw vrije tijd." },
  { id: "sexam-22", topic: "buurt", timeLimitS: 30, text: "Leg uit wat u zou doen als u geluidsoverlast van de buren heeft." },
  { id: "sexam-23", topic: "eten", timeLimitS: 20, text: "Vertel kort wat uw favoriete Nederlandse gerecht is en waarom." },
  { id: "sexam-24", topic: "werk", timeLimitS: 30, text: "Beschrijf een normale werkdag van u, van begin tot eind." },
  { id: "sexam-25", topic: "familie", timeLimitS: 20, text: "Vertel kort iets over uw familie." },
  { id: "sexam-26", topic: "verzekering", timeLimitS: 30, text: "Leg uit waarom een basiszorgverzekering in Nederland verplicht is." },
  { id: "sexam-27", topic: "bibliotheek", timeLimitS: 20, text: "Vertel kort welk boek u het laatst heeft gelezen." },
  { id: "sexam-28", topic: "kinderopvang", timeLimitS: 30, text: "Leg uit hoe u de kinderopvang voor uw kind heeft geregeld." },
  { id: "sexam-29", topic: "afval", timeLimitS: 20, text: "Vertel kort hoe u uw afval scheidt." },
  { id: "sexam-30", topic: "energie", timeLimitS: 30, text: "Leg uit wat u zou doen als uw energierekening plotseling veel hoger is." },
  { id: "sexam-31", topic: "sport", timeLimitS: 20, text: "Vertel kort of u aan sport doet en welke." },
  { id: "sexam-32", topic: "post", timeLimitS: 30, text: "Leg uit wat u zou doen als u een belangrijke brief niet heeft ontvangen." },
  { id: "sexam-33", topic: "bank", timeLimitS: 20, text: "Vertel kort waarom u een bankrekening heeft geopend." },
  { id: "sexam-34", topic: "veiligheid", timeLimitS: 30, text: "Leg uit wat u zou doen als u getuige bent van een ongeluk op straat." },
  { id: "sexam-35", topic: "buurt", timeLimitS: 20, text: "Vertel kort wat u het fijnst vindt aan uw buurt." },
  { id: "sexam-36", topic: "documenten", timeLimitS: 30, text: "Leg uit welke stappen u zou nemen om een uittreksel uit het bevolkingsregister aan te vragen." },
];
